import { resolveModuleView } from './modules/router-module.js';
import { createCvModule } from './modules/cv-module.js';
import { createVideoPresentationModule } from './modules/video-presentation-module.js?v=1.4.0-media-e2e';
import { createAiLiteracyModule } from './modules/ai-literacy-module.js?v=2.16.1-ail-certificate-recovery';
import { createAssessmentModule } from './modules/assessment-module.js?v=4.2.0-media-auth-refresh';
import { createInterviewModule } from './modules/interview-module.js?v=2.3.0-media-auth-refresh';
import { CANDIDATE_LEGAL_VERSION, CANDIDATE_LEGAL_UPDATED_AT, getCandidateLegalBundle } from './modules/candidate-legal-content.js?v=1.3';
import { buildCandidateExperience } from './modules/candidate-experience-content.js?v=1.0.0';
import { createAppFeedbackController } from './modules/app-feedback-controller.js?v=1.1.0';

const API_BASE = 'https://www.clarity-nvl.com/_functions';
const state = {
  uid: new URLSearchParams(location.search).get('uid') || '',
  token: '', payload: null, module: null, locale: 'en', participantLocale: 'en', step: 'welcome', legalDocument: 'privacy'
};
let cvModule = null;
let vpModule = null;
let aiLiteracyModule = null;
let assessmentModule = null;
let interviewModule = null;
let feedbackController = null;
let tokenRefreshPromise = null;
const SUPPORT_DIAGNOSTICS = new URLSearchParams(location.search).get('supportDebug') === '1';

const $ = (id) => document.getElementById(id);
const TEXT = {
  de: {
    support:'Support', heroPrefix:'Willkommen bei', eyebrow:'Sicherer CLARITY-Zugang',
    loadingTitle:'Ihr CLARITY-Link wird geprüft…', loadingText:'Während der sicheren Prüfung werden keine Credits verbraucht.', loadingNotice:'Bitte lassen Sie dieses Fenster geöffnet.',
    workflow:'Workflow', mode:'Modus', language:'Sprache', purpose:'Position / Zweck', scope:'Umfang', accessId:'Zugangs-ID',
    accessSummary:'Zugangsübersicht', company:'Unternehmen', reportLang:'Reportsprache', units:'Reservierte Einheiten', status:'Status',
    welcome:'Ihr sicherer Workflow ist bereit', welcomeText:'Prüfen Sie die Angaben. Durch das Öffnen dieser Seite wurden keine Credits verbraucht.', continue:'Weiter',
    profile:'Teilnehmerprofil', profileText:'Bitte bestätigen Sie die Angaben, die für diesen Workflow verwendet werden.', firstName:'Vorname *', lastName:'Nachname *', email:'E-Mail *', reference:'Referenz (optional)', back:'Zurück', save:'Speichern und weiter',
    consent:'Datenschutz und Transparenz', consentText:'Bitte lesen und bestätigen Sie die notwendigen Erklärungen, bevor das Produktmodul startet.', privacy:'Ich habe die Cookie-, Datenschutz- und KI-Hinweise gelesen und bestätige die dort beschriebene Verarbeitung meiner Daten für diesen Workflow.', ai:'Ich habe die Informationen zur Teilnahme und KI-Analyse gelesen und verstehe, dass bedeutsame endgültige Entscheidungen beim Menschen bleiben.', media:'Ich stimme der erforderlichen Mikrofon- oder Kameraverarbeitung für diesen Workflow zu.', confirm:'Bestätigen und weiter', details:'Details lesen', legalPrivacyTab:'Datenschutz und KI', legalParticipationTab:'Teilnahme und KI-Analyse', legalClose:'Schließen und zurück', legalCloseLabel:'Detailinformationen schließen', legalMeta:'Teilnehmerinformation · Version 1.3',
    productModule:'Produktmodul', moduleText:'Der Universal-App-Router hat die korrekte Produktkonfiguration geladen.', moduleNotice:'Ihr Interview ist vorbereitet. Öffnen Sie das Interview, prüfen Sie Ihr Gerät und starten Sie anschließend.', refresh:'Status aktualisieren', start:'Workflow starten',
    unavailable:'Dieser CLARITY-Link ist nicht verfügbar', unavailableText:'Der Zugang konnte nicht sicher geprüft werden.', unavailableHelp:'Bitte wenden Sie sich an das Unternehmen, das Ihnen den Link gesendet hat.',
    step1:'1 · Willkommen', step1Text:'Zugang prüfen', step2:'2 · Profil', step2Text:'Teilnehmerangaben', step3:'3 · Einwilligung', step3Text:'Datenschutz und Transparenz', step4:'4 · Workflow', step4Text:'Produktmodul',
    noInfo:'Keine Angabe', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive Shell', routerReady:'Modul bereit', modulePending:'Produktmodul folgt', profileError:'Bitte füllen Sie Vorname, Nachname und eine gültige E-Mail-Adresse aus.', consentError:'Bitte bestätigen Sie alle erforderlichen Erklärungen.', genericError:'Der Vorgang konnte nicht abgeschlossen werden.', modulePendingAlert:'Dieses Produktmodul wird in einer folgenden Vertical-Phase aktiviert.', interviewReady:'Das Interview ist bereit.', interviewOpenNotice:'Öffnen Sie das Interview, prüfen Sie Kamera beziehungsweise Mikrofon und starten Sie anschließend.', openInterview:'Interview öffnen'
  },
  en: {
    support:'Support', heroPrefix:'Welcome to', eyebrow:'Secure CLARITY access',
    loadingTitle:'Verifying your CLARITY link…', loadingText:'No credits are consumed while the secure access is checked.', loadingNotice:'Please keep this window open.',
    workflow:'Workflow', mode:'Mode', language:'Language', purpose:'Position / purpose', scope:'Scope', accessId:'Access ID',
    accessSummary:'Access summary', company:'Company', reportLang:'Report language', units:'Reserved units', status:'Status',
    welcome:'Your secure workflow is ready', welcomeText:'Review the information. Opening this page has not consumed any credits.', continue:'Continue',
    profile:'Participant profile', profileText:'Please confirm the details used for this workflow.', firstName:'First name *', lastName:'Last name *', email:'Email *', reference:'Reference (optional)', back:'Back', save:'Save and continue',
    consent:'Privacy and transparency', consentText:'Please read and confirm the required declarations before the product module starts.', privacy:'I have read the Cookie, Privacy and AI Notice and confirm the processing of my data for this workflow as described.', ai:'I have read the participation and AI analysis information and understand that significant final decisions remain human-led.', media:'I agree to the required microphone or camera processing for this workflow.', confirm:'Confirm and continue', details:'Read details', legalPrivacyTab:'Privacy and AI', legalParticipationTab:'Participation and AI analysis', legalClose:'Close and return', legalCloseLabel:'Close detailed information', legalMeta:'Participant information · Version 1.3',
    productModule:'Product module', moduleText:'The Universal App router has loaded the correct product configuration.', moduleNotice:'Your Interview is ready. Open it, check your device once, and then start.', refresh:'Refresh status', start:'Start workflow',
    unavailable:'This CLARITY link is unavailable', unavailableText:'The access could not be verified securely.', unavailableHelp:'Please contact the organisation that sent you the link.',
    step1:'1 · Welcome', step1Text:'Access verification', step2:'2 · Profile', step2Text:'Participant details', step3:'3 · Consent', step3Text:'Privacy and transparency', step4:'4 · Workflow', step4Text:'Product module',
    noInfo:'Not specified', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive shell', routerReady:'Module ready', modulePending:'Product module pending', profileError:'Please enter first name, last name and a valid email address.', consentError:'Please confirm all required declarations.', genericError:'The operation could not be completed.', modulePendingAlert:'This product module is activated in a following vertical phase.', interviewReady:'The Interview is ready.', interviewOpenNotice:'Open the Interview, check your camera or microphone once, and then start.', openInterview:'Open Interview'
  }
};

const LANGUAGE_OVERRIDES={
  es:{eyebrow:'Acceso seguro',loadingTitle:'Verificando su enlace…',loadingText:'No se consume ningún crédito durante la verificación.',loadingNotice:'Mantenga esta ventana abierta.',welcome:'Su flujo seguro está listo',welcomeText:'Revise la información. Abrir esta página no ha consumido créditos.',continue:'Continuar',profile:'Perfil del participante',profileText:'Confirme los datos utilizados para este flujo.',firstName:'Nombre *',lastName:'Apellidos *',reference:'Referencia (opcional)',back:'Atrás',save:'Guardar y continuar',consent:'Privacidad y transparencia',consentText:'Lea y confirme las declaraciones necesarias antes de iniciar el módulo.',privacy:'He leído el Aviso de cookies, privacidad e IA y confirmo el tratamiento descrito de mis datos para este flujo.',ai:'He leído la información de participación y análisis con IA y entiendo que las decisiones finales importantes siguen siendo humanas.',media:'Acepto el tratamiento necesario del micrófono o la cámara para este flujo.',confirm:'Confirmar y continuar',details:'Leer detalles',legalPrivacyTab:'Privacidad e IA',legalParticipationTab:'Participación y análisis con IA',legalClose:'Cerrar y volver',legalCloseLabel:'Cerrar la información detallada',legalMeta:'Información para participantes · Versión 1.3',start:'Iniciar flujo',unavailable:'Este enlace no está disponible',unavailableText:'No se ha podido verificar el acceso de forma segura.',interviewReady:'La entrevista está lista.',interviewOpenNotice:'Abra la entrevista, compruebe la cámara o el micrófono y comience.',openInterview:'Abrir entrevista'},
  fr:{eyebrow:'Accès sécurisé',loadingTitle:'Vérification de votre lien…',loadingText:'Aucun crédit n’est consommé pendant la vérification.',loadingNotice:'Veuillez garder cette fenêtre ouverte.',welcome:'Votre parcours sécurisé est prêt',welcomeText:'Vérifiez les informations. L’ouverture de cette page n’a consommé aucun crédit.',continue:'Continuer',profile:'Profil du participant',profileText:'Veuillez confirmer les informations utilisées pour ce parcours.',firstName:'Prénom *',lastName:'Nom *',reference:'Référence (facultatif)',back:'Retour',save:'Enregistrer et continuer',consent:'Confidentialité et transparence',consentText:'Veuillez lire et confirmer les déclarations requises avant le démarrage du module.',privacy:'J’ai lu la notice relative aux cookies, à la confidentialité et à l’IA et je confirme le traitement décrit de mes données pour ce parcours.',ai:'J’ai lu les informations sur la participation et l’analyse par IA et je comprends que les décisions finales importantes restent humaines.',media:'J’accepte le traitement nécessaire du microphone ou de la caméra pour ce parcours.',confirm:'Confirmer et continuer',details:'Lire les détails',legalPrivacyTab:'Confidentialité et IA',legalParticipationTab:'Participation et analyse par IA',legalClose:'Fermer et revenir',legalCloseLabel:'Fermer les informations détaillées',legalMeta:'Information du participant · Version 1.3',start:'Démarrer',unavailable:'Ce lien n’est pas disponible',unavailableText:'L’accès n’a pas pu être vérifié de manière sécurisée.',interviewReady:'L’entretien est prêt.',interviewOpenNotice:'Ouvrez l’entretien, vérifiez la caméra ou le microphone, puis démarrez.',openInterview:'Ouvrir l’entretien'},
  it:{eyebrow:'Accesso sicuro',loadingTitle:'Verifica del collegamento…',loadingText:'Durante la verifica non viene consumato alcun credito.',loadingNotice:'Mantenga aperta questa finestra.',welcome:'Il flusso sicuro è pronto',welcomeText:'Controlli le informazioni. L’apertura della pagina non ha consumato crediti.',continue:'Continua',profile:'Profilo del partecipante',profileText:'Confermi i dati utilizzati per questo flusso.',firstName:'Nome *',lastName:'Cognome *',reference:'Riferimento (facoltativo)',back:'Indietro',save:'Salva e continua',consent:'Privacy e trasparenza',consentText:'Legga e confermi le dichiarazioni richieste prima dell’avvio del modulo.',privacy:'Ho letto l’Informativa su cookie, privacy e IA e confermo il trattamento descritto dei miei dati per questo flusso.',ai:'Ho letto le informazioni sulla partecipazione e l’analisi tramite IA e comprendo che le decisioni finali importanti restano umane.',media:'Acconsento al trattamento necessario del microfono o della videocamera per questo flusso.',confirm:'Conferma e continua',details:'Leggi i dettagli',legalPrivacyTab:'Privacy e IA',legalParticipationTab:'Partecipazione e analisi IA',legalClose:'Chiudi e torna',legalCloseLabel:'Chiudi le informazioni dettagliate',legalMeta:'Informazioni per il partecipante · Versione 1.3',start:'Avvia flusso',unavailable:'Questo collegamento non è disponibile',unavailableText:'Non è stato possibile verificare l’accesso in modo sicuro.',interviewReady:'L’intervista è pronta.',interviewOpenNotice:'Apra l’intervista, controlli videocamera o microfono e inizi.',openInterview:'Apri intervista'},
  pt:{eyebrow:'Acesso seguro',loadingTitle:'A verificar a ligação…',loadingText:'Nenhum crédito é consumido durante a verificação.',loadingNotice:'Mantenha esta janela aberta.',welcome:'O seu fluxo seguro está pronto',welcomeText:'Reveja as informações. Abrir esta página não consumiu créditos.',continue:'Continuar',profile:'Perfil do participante',profileText:'Confirme os dados utilizados neste fluxo.',firstName:'Nome *',lastName:'Apelido *',reference:'Referência (opcional)',back:'Voltar',save:'Guardar e continuar',consent:'Privacidade e transparência',consentText:'Leia e confirme as declarações necessárias antes do início do módulo.',privacy:'Li o Aviso sobre cookies, privacidade e IA e confirmo o tratamento descrito dos meus dados para este fluxo.',ai:'Li a informação sobre participação e análise por IA e compreendo que as decisões finais importantes continuam a ser humanas.',media:'Aceito o tratamento necessário do microfone ou da câmara para este fluxo.',confirm:'Confirmar e continuar',details:'Ler detalhes',legalPrivacyTab:'Privacidade e IA',legalParticipationTab:'Participação e análise por IA',legalClose:'Fechar e voltar',legalCloseLabel:'Fechar informação detalhada',legalMeta:'Informação do participante · Versão 1.3',start:'Iniciar fluxo',unavailable:'Esta ligação não está disponível',unavailableText:'Não foi possível verificar o acesso com segurança.',interviewReady:'A entrevista está pronta.',interviewOpenNotice:'Abra a entrevista, verifique a câmara ou o microfone e inicie.',openInterview:'Abrir entrevista'},
  nl:{eyebrow:'Beveiligde toegang',loadingTitle:'Uw link wordt gecontroleerd…',loadingText:'Tijdens de controle worden geen credits verbruikt.',loadingNotice:'Laat dit venster open.',welcome:'Uw beveiligde workflow is klaar',welcomeText:'Controleer de informatie. Het openen van deze pagina heeft geen credits verbruikt.',continue:'Doorgaan',profile:'Deelnemersprofiel',profileText:'Bevestig de gegevens voor deze workflow.',firstName:'Voornaam *',lastName:'Achternaam *',reference:'Referentie (optioneel)',back:'Terug',save:'Opslaan en doorgaan',consent:'Privacy en transparantie',consentText:'Lees en bevestig de vereiste verklaringen voordat de module start.',privacy:'Ik heb de kennisgeving over cookies, privacy en AI gelezen en bevestig de beschreven verwerking van mijn gegevens voor deze workflow.',ai:'Ik heb de informatie over deelname en AI-analyse gelezen en begrijp dat belangrijke eindbeslissingen door mensen worden genomen.',media:'Ik stem in met de noodzakelijke verwerking via microfoon of camera voor deze workflow.',confirm:'Bevestigen en doorgaan',details:'Details lezen',legalPrivacyTab:'Privacy en AI',legalParticipationTab:'Deelname en AI-analyse',legalClose:'Sluiten en terug',legalCloseLabel:'Gedetailleerde informatie sluiten',legalMeta:'Deelnemersinformatie · Versie 1.3',start:'Workflow starten',unavailable:'Deze link is niet beschikbaar',unavailableText:'De toegang kon niet veilig worden gecontroleerd.',interviewReady:'Het interview is klaar.',interviewOpenNotice:'Open het interview, controleer camera of microfoon en start daarna.',openInterview:'Interview openen'},
  pl:{eyebrow:'Bezpieczny dostęp',loadingTitle:'Sprawdzanie łącza…',loadingText:'Podczas weryfikacji nie są zużywane żadne kredyty.',loadingNotice:'Pozostaw to okno otwarte.',welcome:'Bezpieczny proces jest gotowy',welcomeText:'Sprawdź informacje. Otwarcie tej strony nie zużyło kredytów.',continue:'Kontynuuj',profile:'Profil uczestnika',profileText:'Potwierdź dane używane w tym procesie.',firstName:'Imię *',lastName:'Nazwisko *',reference:'Referencja (opcjonalnie)',back:'Wstecz',save:'Zapisz i kontynuuj',consent:'Prywatność i przejrzystość',consentText:'Przeczytaj i potwierdź wymagane oświadczenia przed uruchomieniem modułu.',privacy:'Przeczytałem(-am) informację o cookies, prywatności i AI oraz potwierdzam opisane przetwarzanie moich danych w tym procesie.',ai:'Przeczytałem(-am) informacje o udziale i analizie AI oraz rozumiem, że ważne decyzje końcowe pozostają po stronie człowieka.',media:'Wyrażam zgodę na wymagane użycie mikrofonu lub kamery w tym procesie.',confirm:'Potwierdź i kontynuuj',details:'Czytaj szczegóły',legalPrivacyTab:'Prywatność i AI',legalParticipationTab:'Udział i analiza AI',legalClose:'Zamknij i wróć',legalCloseLabel:'Zamknij szczegółowe informacje',legalMeta:'Informacja dla uczestnika · Wersja 1.3',start:'Uruchom proces',unavailable:'To łącze jest niedostępne',unavailableText:'Nie udało się bezpiecznie zweryfikować dostępu.',interviewReady:'Rozmowa jest gotowa.',interviewOpenNotice:'Otwórz rozmowę, sprawdź kamerę lub mikrofon, a następnie rozpocznij.',openInterview:'Otwórz rozmowę'},
  tr:{eyebrow:'Güvenli erişim',loadingTitle:'Bağlantınız doğrulanıyor…',loadingText:'Doğrulama sırasında kredi kullanılmaz.',loadingNotice:'Lütfen bu pencereyi açık tutun.',welcome:'Güvenli iş akışınız hazır',welcomeText:'Bilgileri kontrol edin. Bu sayfayı açmak kredi tüketmedi.',continue:'Devam',profile:'Katılımcı profili',profileText:'Bu iş akışında kullanılan bilgileri onaylayın.',firstName:'Ad *',lastName:'Soyad *',reference:'Referans (isteğe bağlı)',back:'Geri',save:'Kaydet ve devam et',consent:'Gizlilik ve şeffaflık',consentText:'Modül başlamadan önce gerekli beyanları okuyup onaylayın.',privacy:'Çerez, Gizlilik ve YZ Bildirimini okudum ve verilerimin bu akış için açıklanan şekilde işlenmesini onaylıyorum.',ai:'Katılım ve YZ analizi bilgisini okudum ve önemli nihai kararların insan gözetiminde kaldığını anlıyorum.',media:'Bu akış için gerekli mikrofon veya kamera işlemesini kabul ediyorum.',confirm:'Onayla ve devam et',details:'Ayrıntıları oku',legalPrivacyTab:'Gizlilik ve YZ',legalParticipationTab:'Katılım ve YZ analizi',legalClose:'Kapat ve geri dön',legalCloseLabel:'Ayrıntılı bilgiyi kapat',legalMeta:'Katılımcı bilgisi · Sürüm 1.3',start:'İş akışını başlat',unavailable:'Bu bağlantı kullanılamıyor',unavailableText:'Erişim güvenli biçimde doğrulanamadı.',interviewReady:'Mülakat hazır.',interviewOpenNotice:'Mülakatı açın, kamerayı veya mikrofonu kontrol edin ve başlayın.',openInterview:'Mülakatı aç'},
  ar:{eyebrow:'وصول آمن',loadingTitle:'جارٍ التحقق من الرابط…',loadingText:'لا يتم استهلاك أي رصيد أثناء التحقق.',loadingNotice:'يرجى إبقاء هذه النافذة مفتوحة.',welcome:'سير العمل الآمن جاهز',welcomeText:'راجع المعلومات. لم يؤد فتح هذه الصفحة إلى استهلاك أي رصيد.',continue:'متابعة',profile:'ملف المشارك',profileText:'يرجى تأكيد البيانات المستخدمة في سير العمل.',firstName:'الاسم الأول *',lastName:'اسم العائلة *',reference:'المرجع (اختياري)',back:'رجوع',save:'حفظ ومتابعة',consent:'الخصوصية والشفافية',consentText:'يرجى قراءة الإقرارات المطلوبة وتأكيدها قبل بدء الوحدة.',privacy:'قرأت إشعار ملفات الارتباط والخصوصية والذكاء الاصطناعي وأؤكد معالجة بياناتي لهذا المسار كما هو موضح.',ai:'قرأت معلومات المشاركة والتحليل بالذكاء الاصطناعي وأفهم أن القرارات النهائية المهمة تبقى تحت إشراف البشر.',media:'أوافق على المعالجة المطلوبة للميكروفون أو الكاميرا في هذا المسار.',confirm:'تأكيد ومتابعة',details:'قراءة التفاصيل',legalPrivacyTab:'الخصوصية والذكاء الاصطناعي',legalParticipationTab:'المشاركة وتحليل الذكاء الاصطناعي',legalClose:'إغلاق والعودة',legalCloseLabel:'إغلاق المعلومات التفصيلية',legalMeta:'معلومات المشارك · الإصدار 1.3',start:'بدء سير العمل',unavailable:'هذا الرابط غير متاح',unavailableText:'تعذر التحقق من الوصول بأمان.',interviewReady:'المقابلة جاهزة.',interviewOpenNotice:'افتح المقابلة وتحقق من الكاميرا أو الميكروفون ثم ابدأ.',openInterview:'فتح المقابلة'}
};
Object.entries(LANGUAGE_OVERRIDES).forEach(([code,copy])=>{TEXT[code]={...TEXT.en,...copy}});
function normalizeUiLocale(value='en'){const code=String(value||'en').toLowerCase().split(/[-_]/)[0];return TEXT[code]?code:'en'}

const ACCESS_ERROR_COPY={
  de:{used:['Dieser Link wurde bereits verwendet','Der zugehörige Vorgang wurde bereits vollständig abgeschlossen. Über diesen Link können keine Inhalte, Teilnehmerdaten oder Bewertungen mehr geöffnet werden.','Bitte wenden Sie sich an das Unternehmen, von dem Sie den Link erhalten haben.'],expired:['Dieser Link ist abgelaufen','Die Gültigkeitsdauer dieses Zugangs ist beendet. Es wurden keine Teilnehmerdaten geladen.','Bitte wenden Sie sich an das Unternehmen, von dem Sie den Link erhalten haben.'],invalid:['Dieser Link ist nicht gültig','Der Zugang konnte nicht sicher bestätigt werden. Es wurden keine Teilnehmerdaten geladen.','Bitte prüfen Sie den vollständigen Link oder wenden Sie sich an das sendende Unternehmen.']},
  en:{used:['This link has already been used','The associated workflow has already been completed. No content, participant data or rating can be opened through this link.','Please contact the organisation that sent you the link.'],expired:['This link has expired','The validity period for this access has ended. No participant data was loaded.','Please contact the organisation that sent you the link.'],invalid:['This link is not valid','The access could not be verified securely. No participant data was loaded.','Please check the complete link or contact the organisation that sent it.']},
  es:{used:['Este enlace ya se ha utilizado','El proceso asociado ya ha finalizado. Este enlace ya no permite abrir contenidos, datos del participante ni valoraciones.','Póngase en contacto con la organización que le envió el enlace.'],expired:['Este enlace ha caducado','El período de validez del acceso ha terminado. No se cargaron datos del participante.','Póngase en contacto con la organización que le envió el enlace.'],invalid:['Este enlace no es válido','No se pudo verificar el acceso de forma segura. No se cargaron datos del participante.','Compruebe el enlace completo o contacte con la organización remitente.']},
  fr:{used:['Ce lien a déjà été utilisé','Le parcours associé est déjà terminé. Aucun contenu, donnée de participant ou avis ne peut être ouvert avec ce lien.','Veuillez contacter l’organisation qui vous a envoyé le lien.'],expired:['Ce lien a expiré','La durée de validité de cet accès est terminée. Aucune donnée de participant n’a été chargée.','Veuillez contacter l’organisation qui vous a envoyé le lien.'],invalid:['Ce lien n’est pas valide','L’accès n’a pas pu être vérifié de manière sécurisée. Aucune donnée de participant n’a été chargée.','Vérifiez le lien complet ou contactez l’organisation expéditrice.']},
  it:{used:['Questo collegamento è già stato utilizzato','Il processo associato è già stato completato. Questo collegamento non consente più di aprire contenuti, dati del partecipante o valutazioni.','Contatti l’organizzazione che le ha inviato il collegamento.'],expired:['Questo collegamento è scaduto','Il periodo di validità dell’accesso è terminato. Non sono stati caricati dati del partecipante.','Contatti l’organizzazione che le ha inviato il collegamento.'],invalid:['Questo collegamento non è valido','Non è stato possibile verificare l’accesso in modo sicuro. Non sono stati caricati dati del partecipante.','Controlli il collegamento completo o contatti l’organizzazione mittente.']},
  pt:{used:['Esta ligação já foi utilizada','O processo associado já foi concluído. Esta ligação já não permite abrir conteúdos, dados do participante ou avaliações.','Contacte a organização que lhe enviou a ligação.'],expired:['Esta ligação expirou','O período de validade deste acesso terminou. Não foram carregados dados do participante.','Contacte a organização que lhe enviou a ligação.'],invalid:['Esta ligação não é válida','Não foi possível verificar o acesso com segurança. Não foram carregados dados do participante.','Verifique a ligação completa ou contacte a organização remetente.']},
  nl:{used:['Deze link is al gebruikt','De bijbehorende workflow is al afgerond. Via deze link kunnen geen inhoud, deelnemersgegevens of beoordelingen meer worden geopend.','Neem contact op met de organisatie die u de link heeft gestuurd.'],expired:['Deze link is verlopen','De geldigheidsduur van deze toegang is verstreken. Er zijn geen deelnemersgegevens geladen.','Neem contact op met de organisatie die u de link heeft gestuurd.'],invalid:['Deze link is niet geldig','De toegang kon niet veilig worden geverifieerd. Er zijn geen deelnemersgegevens geladen.','Controleer de volledige link of neem contact op met de verzendende organisatie.']},
  pl:{used:['Ten link został już wykorzystany','Powiązany proces został już zakończony. Za pomocą tego linku nie można już otworzyć treści, danych uczestnika ani oceny.','Skontaktuj się z organizacją, od której otrzymałeś(-aś) link.'],expired:['Ten link wygasł','Okres ważności tego dostępu dobiegł końca. Nie wczytano danych uczestnika.','Skontaktuj się z organizacją, od której otrzymałeś(-aś) link.'],invalid:['Ten link jest nieprawidłowy','Nie udało się bezpiecznie zweryfikować dostępu. Nie wczytano danych uczestnika.','Sprawdź pełny link lub skontaktuj się z organizacją wysyłającą.']},
  tr:{used:['Bu bağlantı daha önce kullanılmış','İlgili süreç zaten tamamlanmış. Bu bağlantı üzerinden içerik, katılımcı verileri veya değerlendirme artık açılamaz.','Bağlantıyı gönderen kuruluşla iletişime geçin.'],expired:['Bu bağlantının süresi dolmuş','Bu erişimin geçerlilik süresi sona ermiş. Katılımcı verisi yüklenmedi.','Bağlantıyı gönderen kuruluşla iletişime geçin.'],invalid:['Bu bağlantı geçerli değil','Erişim güvenli biçimde doğrulanamadı. Katılımcı verisi yüklenmedi.','Tam bağlantıyı kontrol edin veya gönderen kuruluşla iletişime geçin.']},
  ar:{used:['تم استخدام هذا الرابط من قبل','اكتمل الإجراء المرتبط بهذا الرابط. لا يمكن فتح أي محتوى أو بيانات مشارك أو تقييم من خلاله.','يرجى التواصل مع الجهة التي أرسلت إليك الرابط.'],expired:['انتهت صلاحية هذا الرابط','انتهت مدة صلاحية هذا الوصول. لم يتم تحميل أي بيانات للمشارك.','يرجى التواصل مع الجهة التي أرسلت إليك الرابط.'],invalid:['هذا الرابط غير صالح','تعذر التحقق من الوصول بأمان. لم يتم تحميل أي بيانات للمشارك.','تحقق من الرابط كاملًا أو تواصل مع الجهة المرسلة.']}
};
function accessErrorCopy(code=''){
  const normalized=String(code||'').toUpperCase();
  if(normalized==='UNIVERSAL_ACCESS_ALREADY_USED')return(ACCESS_ERROR_COPY[state.locale]||ACCESS_ERROR_COPY.en).used;
  if(normalized==='UNIVERSAL_ACCESS_EXPIRED')return(ACCESS_ERROR_COPY[state.locale]||ACCESS_ERROR_COPY.en).expired;
  const invalidCodes=new Set(['UNIVERSAL_UID_REQUIRED','UNIVERSAL_RUNTIME_NOT_FOUND','UNIVERSAL_ACCESS_UNAVAILABLE','UNIVERSAL_ACCESS_NOT_PLATFORM_MANAGED','UNIVERSAL_TOKEN_INVALID','UNIVERSAL_TOKEN_SCOPE_INVALID','UNIVERSAL_TOKEN_UID_MISMATCH','UNIVERSAL_TOKEN_COMPANY_MISMATCH','UNIVERSAL_TOKEN_ACCESS_MISMATCH','UNIVERSAL_TOKEN_NONCE_MISMATCH']);
  if(invalidCodes.has(normalized))return(ACCESS_ERROR_COPY[state.locale]||ACCESS_ERROR_COPY.en).invalid;
  return[t('unavailable'),t('unavailableText'),t('unavailableHelp')]
}

function t(key,...args){const value=TEXT[state.locale]?.[key]??TEXT.en[key]??key;return typeof value==='function'?value(...args):value}
function show(id){['loadingView','welcomeView','profileView','consentView','moduleView','assessmentView','cvView','cvProcessingView','cvCompleteView','vpView','vpProcessingView','vpCompleteView','aiLiteracyView','errorView'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id))}
function setStep(step){state.step=step;const order=['welcome','profile','consent','module'];const pos=order.indexOf(step);document.querySelectorAll('.step').forEach((el,i)=>{el.classList.toggle('active',i===pos);el.classList.toggle('done',i<pos)})}
function langName(code){return({de:'Deutsch',en:'English',fr:'Français',es:'Español',it:'Italiano',nl:'Nederlands',pt:'Português',pl:'Polski',tr:'Türkçe',ar:'العربية'})[code]||String(code||'—').toUpperCase()}
function modeName(mode){const map={audio:'Audio',video:'Video',mix:'Mix',audio_chat:'Audio + Chat',video_chat:'Video + Chat',chat:'Chat',upload:'Upload',standard:'Standard'};return map[mode]||String(mode||'—').replaceAll('_',' ')}
let legalReturnFocus=null;
function renderLegalDocument(type=state.legalDocument){
  const requested=type==='participation'?'participation':'privacy';
  const bundle=getCandidateLegalBundle(state.locale);
  const documentCopy=bundle.documents[requested]||bundle.documents.privacy;
  state.legalDocument=requested;
  $('legalDialogTitle').textContent=documentCopy.title;
  $('legalDialogMeta').textContent=t('legalMeta');
  $('legalTabPrivacy').classList.toggle('active',requested==='privacy');
  $('legalTabParticipation').classList.toggle('active',requested==='participation');
  $('legalTabPrivacy').setAttribute('aria-selected',String(requested==='privacy'));
  $('legalTabParticipation').setAttribute('aria-selected',String(requested==='participation'));
  const body=$('legalDialogBody');
  body.replaceChildren();
  const intro=document.createElement('p');intro.className='legal-intro';intro.textContent=documentCopy.intro;body.appendChild(intro);
  documentCopy.sections.forEach(([heading,text])=>{const section=document.createElement('section');section.className='legal-section';const h=document.createElement('h3');h.textContent=heading;const p=document.createElement('p');p.textContent=text;section.append(h,p);body.appendChild(section)});
  body.scrollTop=0;
}
function openLegalDocument(type,trigger=null){
  legalReturnFocus=trigger||document.activeElement;
  renderLegalDocument(type);
  const dialog=$('legalDialog');
  if(!dialog.open)dialog.showModal();
  requestAnimationFrame(()=>$('legalDialogBody')?.focus());
}
function closeLegalDialog(){if($('legalDialog')?.open)$('legalDialog').close()}
function installProcessingBrandLogo(logoUrl='',options={}){
  const mode=resolveBrandingMode({brandingMode:options.mode||'clarity'}),secondaryLogoUrl=String(options.secondaryLogoUrl||'').trim();
  document.querySelectorAll('.processing-orbit').forEach(orbit=>{
    orbit.classList.add('branded-processing-orbit');
    let core=orbit.querySelector('.processing-brand-core');
    if(!core){core=document.createElement('div');core.className='processing-brand-core';const image=document.createElement('img');image.alt='';image.setAttribute('aria-hidden','true');core.appendChild(image);orbit.appendChild(core)}
    core.classList.toggle('co-branding',mode==='cobranded'&&Boolean(secondaryLogoUrl));
    core.dataset.brandingMode=mode;
    const image=core.querySelector('img:not(.processing-brand-secondary)');
    image.onerror=()=>image.removeAttribute('src');
    if(logoUrl)image.src=logoUrl;else image.removeAttribute('src');
    let secondary=core.querySelector('.processing-brand-secondary');
    if(mode==='cobranded'&&secondaryLogoUrl){
      if(!secondary){secondary=document.createElement('img');secondary.className='processing-brand-secondary';secondary.alt='';secondary.setAttribute('aria-hidden','true');core.appendChild(secondary)}
      secondary.onerror=()=>secondary.remove();
      secondary.src=secondaryLogoUrl;
    }else secondary?.remove();
  });
}
function applyLocale(){
  document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==='ar'?'rtl':'ltr';$('langBtn').textContent=state.locale===state.participantLocale?'EN':state.participantLocale.toUpperCase();
  const map={eyebrow:'eyebrow',heroPrefix:'heroPrefix',loadingTitle:'loadingTitle',loadingText:'loadingText',loadingNotice:'loadingNotice',metaWorkflowLabel:'workflow',metaModeLabel:'mode',metaLanguageLabel:'language',metaPurposeLabel:'purpose',metaQuestionsLabel:'scope',metaUidLabel:'accessId',summaryTitle:'accessSummary',summaryCompanyLabel:'company',summaryReportLabel:'reportLang',summaryUnitsLabel:'units',summaryStatusLabel:'status',welcomeTitle:'welcome',welcomeText:'welcomeText',continueProfileBtn:'continue',profileTitle:'profile',profileText:'profileText',firstNameLabel:'firstName',lastNameLabel:'lastName',emailLabel:'email',referenceLabel:'reference',backWelcomeBtn:'back',saveProfileBtn:'save',consentTitle:'consent',consentText:'consentText',privacyConsentText:'privacy',aiConsentText:'ai',mediaConsentText:'media',privacyDetailsBtn:'details',aiDetailsBtn:'details',mediaDetailsBtn:'details',backProfileBtn:'back',saveConsentBtn:'confirm',legalTabPrivacy:'legalPrivacyTab',legalTabParticipation:'legalParticipationTab',legalDialogCloseBtn:'legalClose',moduleViewTitle:'productModule',moduleViewText:'moduleText',moduleNotice:'moduleNotice',statusBtn:'refresh',startModuleBtn:'start',errorTitle:'unavailable',errorText:'unavailableText',errorHelp:'unavailableHelp',step1Title:'step1',step1Text:'step1Text',step2Title:'step2',step2Text:'step2Text',step3Title:'step3',step3Text:'step3Text',step4Title:'step4',step4Text:'step4Text'};
  Object.entries(map).forEach(([id,k])=>{if($(id))$(id).textContent=t(k)});$('legalDialogCloseX')?.setAttribute('aria-label',t('legalCloseLabel'));if($('legalDialog')?.open)renderLegalDocument();renderPayload();cvModule?.applyLocale();vpModule?.applyLocale();aiLiteracyModule?.applyLocale();assessmentModule?.applyLocale();feedbackController?.applyLocale();
}
function normalizeWixImageUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw))return raw;if(/^wix:image:\/\//i.test(raw)){const match=raw.match(/^wix:image:\/\/v1\/([^/]+)\//i)||raw.match(/^wix:image:\/\/([^/]+)\//i);return match?.[1]?`https://static.wixstatic.com/media/${encodeURIComponent(match[1])}`:''}return''}
function normalizeBrandingMode(value){const raw=String(value||'clarity').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');if(['co_branding','cobranding','co_branded','cobranded','customer','recruitment'].includes(raw))return'cobranded';if(['white_label','whitelabel','white_branded'].includes(raw))return'whitelabel';return'clarity'}
function resolveBrandingMode(branding={}){const requested=normalizeBrandingMode(branding.requestedBrandingMode),configured=normalizeBrandingMode(branding.brandingMode||branding.mode),customerMode=requested==='whitelabel'||configured==='whitelabel'||requested==='cobranded'||configured==='cobranded'||branding.coBrandingEnabled===true;if(branding.whiteLabelEnabled===true||branding.hideClarityBrand===true||branding.clarityBrandVisible===false||(customerMode&&branding.poweredByClarityVisible===false)||requested==='whitelabel'||configured==='whitelabel')return'whitelabel';if(branding.coBrandingEnabled===true||requested==='cobranded'||configured==='cobranded')return'cobranded';return'clarity'}
function assetCandidates(value){if(!value)return[];if(typeof value==='string')return[value];if(typeof value!=='object'||Array.isArray(value))return[];return[value.publicUrl,value.logoPublicUrl,value.previewUrl,value.logoPreviewUrl,value.fileUrl,value.logoFileUrl,value.downloadUrl,value.src,value.url,value.assetUrl,value.mediaUrl]}
function resolveBrandLogoSource(branding={},mode='clarity'){const explicitCustomer=[branding.customerLogoUrl,branding.companyLogoUrl,branding.customerLogo,branding.companyLogo,branding.customerLogoCandidates,branding.metadata?.customerLogoUrl,branding.metadata?.companyLogoUrl];const generic=[branding.logoUrl,branding.logoPublicUrl,branding.publicLogoUrl,branding.primaryLogo,branding.logo,branding.logoAsset,branding.media,branding.metadata?.logoPublicUrl,branding.metadata?.logoFileUrl];const values=mode==='whitelabel'?[...explicitCustomer,...generic]:[...explicitCustomer,...generic];for(const value of values){const items=Array.isArray(value)?value:[value];for(const item of items){for(const candidate of assetCandidates(item)){const url=normalizeWixImageUrl(candidate);if(url)return url}}}return''}
function preloadImage(url,timeoutMs=8000){return new Promise((resolve,reject)=>{if(!url)return reject(Object.assign(new Error('Brand logo URL missing.'),{code:'BRAND_LOGO_URL_MISSING'}));const image=new Image();let done=false;const finish=(fn,value)=>{if(done)return;done=true;clearTimeout(timer);fn(value)};const timer=setTimeout(()=>finish(reject,Object.assign(new Error('Brand logo preload timed out.'),{code:'BRAND_LOGO_PRELOAD_TIMEOUT'})),timeoutMs);image.onload=()=>finish(resolve,url);image.onerror=()=>finish(reject,Object.assign(new Error('Brand logo could not be loaded.'),{code:'BRAND_LOGO_LOAD_FAILED',details:{url}}));image.referrerPolicy='no-referrer';image.src=url})}
function revealApp(){document.body.classList.remove('branding-pending');document.body.classList.add('branding-ready');$('appShell')?.setAttribute('aria-hidden','false');$('bootstrapGate')?.classList.add('ready');$('bootstrapGate')?.setAttribute('aria-busy','false')}
async function applyBranding(branding={}){const colors=branding.colors||{},root=document.documentElement,mode=resolveBrandingMode(branding),white=mode==='whitelabel',co=mode==='cobranded';if(colors.primary)root.style.setProperty('--navy',colors.primary);if(colors.accent)root.style.setProperty('--cyan',colors.accent);if(colors.secondary)root.style.setProperty('--violet',colors.secondary);if(colors.highlight||colors.magenta)root.style.setProperty('--magenta',colors.highlight||colors.magenta);const customerName=branding.reportBrandName||branding.brandName||branding.companyName||'Company';$('brandName').textContent=white||co?customerName:'CLARITY';$('productLine').textContent=white?(branding.candidatePageSettings?.productLine||branding.productLine||''):(co?(branding.poweredByClarityVisible===false?'':'Powered by CLARITY'):(branding.legalProductName||'CLARITY Decision Intelligence Platform'));const logo=resolveBrandLogoSource(branding,mode);const logoEl=$('brandLogo');logoEl.hidden=true;logoEl.removeAttribute('src');logoEl.style.visibility='visible';let appliedLogo='';if(logo&&branding.customerLogoVisible!==false){try{await preloadImage(logo);appliedLogo=logo}catch(error){SUPPORT_DIAGNOSTICS&&console.warn('[CLARITY APP] Branding asset fallback',error)}}const customerLogoApplied=Boolean(logo&&appliedLogo);if(!appliedLogo&&!white){try{await preloadImage('./assets/clarity-logo.png');appliedLogo='./assets/clarity-logo.png'}catch(_){}}if(appliedLogo){logoEl.src=appliedLogo;logoEl.alt=`${white||co?customerName:'CLARITY'} logo`;logoEl.hidden=false;const favicon=$('appFavicon');if(favicon)favicon.href=appliedLogo}else{logoEl.hidden=true}const coLoader=co&&customerLogoApplied;const loaderLogo=white?appliedLogo:(coLoader?appliedLogo:'./assets/clarity-logo.png');const loaderSecondary=coLoader?'./assets/clarity-logo.png':'';installProcessingBrandLogo(loaderLogo,{mode:white?'whitelabel':coLoader?'cobranded':'clarity',secondaryLogoUrl:loaderSecondary});const footer=$('footerLeft');if(footer)footer.textContent=white?(branding.footerBrandName||customerName):(co?`${customerName}${branding.poweredByClarityVisible===false?'':' · Powered by CLARITY'}`:'CLARITY Decision Intelligence Platform');return{mode,whiteLabel:white,coBranding:co,logoUrl:appliedLogo,loaderLogoUrl:loaderLogo,loaderSecondaryLogoUrl:loaderSecondary,assetFallback:Boolean(logo&&!appliedLogo)}}
function renderPayload(){
  if(!state.payload)return;const r=state.payload.runtime||{},b=state.payload.branding||{},m=state.module||resolveModuleView(state.payload,state.locale);state.module=m;
  const brandMode=resolveBrandingMode(b);const experience=buildCandidateExperience({runtime:r,branding:b,brandingMode:brandMode},state.locale);
  $('eyebrow').textContent=experience.eyebrow;$('heroTitle').textContent=experience.welcomeTitle;$('heroDescription').textContent=experience.context||experience.product;
  $('welcomeText').textContent=experience.summary;$('welcomeWhatTitle').textContent=experience.whatTitle;$('welcomeWhatText').textContent=experience.context||experience.summary;$('welcomeHowTitle').textContent=experience.howTitle;
  $('welcomeProductTag').textContent=experience.product;$('welcomeModeTag').textContent=experience.modeLabel;$('welcomeQuestionTag').textContent=experience.questionLabel;$('welcomeQuestionTag').classList.toggle('hidden',!experience.questionLabel);
  ['welcomeStep1','welcomeStep2','welcomeStep3'].forEach((id,index)=>{if($(id))$(id).textContent=experience.steps[index]||''});
  $('preparationSummary').textContent=experience.tipsSummary;const prepList=$('preparationList');if(prepList){prepList.replaceChildren();experience.tips.forEach(value=>{const item=document.createElement('li');item.textContent=value;prepList.appendChild(item)})}
  $('moduleViewTitle').textContent=experience.readyTitle;$('moduleViewText').textContent=experience.readyText;$('moduleNotice').textContent=experience.tips[experience.tips.length-1]||experience.readyText;
  $('finalModuleIcon').textContent=m.icon||'CL';$('finalModuleTitle').textContent=experience.product;$('finalModuleDescription').textContent=experience.summary;
  $('startModuleBtn').disabled=!m.startEnabled;$('startModuleBtn').textContent=experience.startLabel;$('mediaConsentRow').classList.toggle('hidden',!m.media);
  const isInterview=String(r.productKey||'').toLowerCase()==='interview';document.body.classList.toggle('interview-product',isInterview);$('statusBtn')?.classList.add('hidden');
  applyBranding(b);
}
async function apiRaw(path,{method='POST',body=null,query={},timeoutMs=120000}={}){
  const url=new URL(`${API_BASE}/${path}`);
  Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,v)});
  const controller=typeof AbortController!=='undefined'?new AbortController():null;
  const boundedTimeout=Math.max(5000,Math.min(180000,Number(timeoutMs)||120000));
  const startedAt=Date.now();
  const timer=controller?setTimeout(()=>controller.abort(),boundedTimeout):null;
  try{
    const response=await fetch(url,{method,headers:{'Content-Type':'application/json','Accept':'application/json'},body:body?JSON.stringify(body):undefined,credentials:'omit',cache:'no-store',signal:controller?.signal});
    const data=await response.json().catch(()=>({}));
    if(!response.ok||data?.ok===false){
      const errorPayload=typeof data?.error==='object'?data.error:{};
      const e=new Error(errorPayload.message||data?.message||`HTTP ${response.status}`);
      e.code=errorPayload.code||data?.code||data?.error||`HTTP_${response.status}`;
      e.details=errorPayload.details||data?.details||null;
      e.httpStatus=response.status;e.durationMs=Date.now()-startedAt;throw e
    }
    return data
  }catch(error){
    if(error?.name==='AbortError'){
      const e=new Error(`Request '${path}' timed out after ${boundedTimeout} ms.`);
      e.code='UNIVERSAL_API_TIMEOUT';e.transport=true;e.path=path;e.timeoutMs=boundedTimeout;e.durationMs=Date.now()-startedAt;throw e
    }
    throw error
  }finally{if(timer)clearTimeout(timer)}
}
function isUniversalTokenError(error){return['UNIVERSAL_TOKEN_INVALID','UNIVERSAL_TOKEN_NONCE_MISMATCH','UNIVERSAL_TOKEN_SCOPE_INVALID','UNIVERSAL_TOKEN_UID_MISMATCH','UNIVERSAL_TOKEN_COMPANY_MISMATCH','UNIVERSAL_TOKEN_ACCESS_MISMATCH'].includes(String(error?.code||''))}
async function refreshUniversalToken(){if(tokenRefreshPromise)return tokenRefreshPromise;tokenRefreshPromise=(async()=>{const data=await apiRaw('v2AppBootstrap',{method:'GET',query:{uid:state.uid,userAgent:navigator.userAgent,deviceClass:deviceClass()}});if(!data?.token)throw Object.assign(new Error('The Universal App session could not be renewed.'),{code:'UNIVERSAL_TOKEN_REFRESH_FAILED'});state.token=data.token;state.payload={...(state.payload||{}),...data,runtime:{...(state.payload?.runtime||{}),...(data.runtime||{})},branding:data.branding||state.payload?.branding};state.module=resolveModuleView(state.payload,state.locale);renderPayload();return state.token})().finally(()=>{tokenRefreshPromise=null});return tokenRefreshPromise}
async function api(path,options={}){const request={method:options.method||'POST',body:options.body?{...options.body}:null,query:{...(options.query||{})},timeoutMs:options.timeoutMs};try{return await apiRaw(path,request)}catch(error){if(path==='v2AppBootstrap'||!isUniversalTokenError(error))throw error;await refreshUniversalToken();if(request.body&&('token'in request.body||'sessionToken'in request.body)){request.body.token=state.token;delete request.body.sessionToken}return apiRaw(path,request)}}
function deviceClass(){const w=Math.min(screen.width||innerWidth,innerWidth);return w<600?'mobile':w<1024?'tablet':'desktop'}
function prefill(){const p=state.payload?.runtime?.candidateProfile||{};$('firstName').value=p.firstName||'';$('lastName').value=p.lastName||'';$('email').value=p.email||'';$('externalReference').value=p.externalReference||''}
function setActionBusy(button,busy){if(!button)return;button.disabled=!!busy;button.classList.toggle('busy',!!busy);button.setAttribute('aria-busy',busy?'true':'false')}
function secureAccessLockdown(){
  feedbackController?.destroy();state.token='';state.payload=null;state.module=null;
  document.body.classList.remove('interview-production-mode','feedback-experience-active');
  const feedback=$('appFeedbackLayer');feedback?.classList.add('hidden');feedback?.setAttribute('aria-hidden','true');$('feedbackReturnBtn')?.classList.add('hidden');
  document.querySelectorAll('#assessmentView iframe,#interviewModuleFrame,#aiLiteracyFrame').forEach(frame=>{try{frame.src='about:blank'}catch(_){}});
  document.querySelectorAll('video').forEach(video=>{try{video.pause();const stream=video.srcObject;stream?.getTracks?.().forEach(track=>track.stop());video.srcObject=null}catch(_){}});
  ['firstName','lastName','email','externalReference'].forEach(id=>{if($(id))$(id).value=''});
}
async function fail(error){secureAccessLockdown();state.locale=normalizeUiLocale(navigator.language||'en');state.participantLocale=state.locale;document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==='ar'?'rtl':'ltr';applyLocale();const [title,message,help]=accessErrorCopy(error?.code);try{await applyBranding({brandingMode:'clarity',brandName:'CLARITY',legalProductName:'CLARITY Decision Intelligence Platform',logoUrl:'./assets/clarity-logo.png'})}catch(_){}revealApp();show('errorView');$('errorTitle').textContent=title;$('errorText').textContent=message;$('errorHelp').textContent=help;$('errorCode').textContent=error?.code||'UNIVERSAL_APP_ERROR'}
async function bootstrap(){if(!state.uid)return fail({code:'UNIVERSAL_UID_REQUIRED',message:t('unavailableText')});try{const data=await api('v2AppBootstrap',{method:'GET',query:{uid:state.uid,userAgent:navigator.userAgent,deviceClass:deviceClass()}});state.payload=data;state.token=data.token||'';state.participantLocale=normalizeUiLocale(data.runtime?.participantLang||data.runtime?.userCommLang||'en');state.locale=state.participantLocale;state.module=resolveModuleView(data,state.locale);prefill();applyLocale();await applyBranding(data.branding||data.runtime?.brandingSnapshot||{});setStep('welcome');show('welcomeView');revealApp();feedbackController?.probe()}catch(e){await fail(e)}}
async function saveProfile(){const button=$('saveProfileBtn'),profile={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),email:$('email').value.trim(),externalReference:$('externalReference').value.trim()};if(button?.getAttribute('aria-busy')==='true')return;if(!profile.firstName||!profile.lastName||!/^\S+@\S+\.\S+$/.test(profile.email))return alert(t('profileError'));setActionBusy(button,true);try{const data=await api('v2AppProfile',{body:{token:state.token,uid:state.uid,profile}});state.payload.runtime={...state.payload.runtime,...data.runtime};setStep('consent');show('consentView')}catch(e){alert(e.message||t('genericError'))}finally{setActionBusy(button,false)}}
async function saveConsent(){const button=$('saveConsentBtn'),mediaOk=!state.module?.media||$('consentMediaRequired').checked;if(button?.getAttribute('aria-busy')==='true')return;if(!$('consentPrivacyRequired').checked||!$('consentAiRequired').checked||!mediaOk)return alert(t('consentError'));setActionBusy(button,true);try{const data=await api('v2AppConsent',{body:{token:state.token,uid:state.uid,accepted:true,privacyAccepted:true,aiInteractionAccepted:true,mediaAccepted:state.module?.media===true,version:CANDIDATE_LEGAL_VERSION,noticeLocale:state.locale,noticeUpdatedAt:CANDIDATE_LEGAL_UPDATED_AT,privacyNoticeVersion:CANDIDATE_LEGAL_VERSION,participationNoticeVersion:CANDIDATE_LEGAL_VERSION,noticeDocuments:['cookie_privacy_ai','participation_data_processing_ai']}});state.payload.runtime={...state.payload.runtime,...data.runtime};renderPayload();setStep('module');show('moduleView')}catch(e){alert(e.message||t('genericError'))}finally{setActionBusy(button,false)}}
async function refreshStatus(){const button=$('statusBtn');if(button?.getAttribute('aria-busy')==='true')return;setActionBusy(button,true);try{const data=await api('v2AppStatus',{body:{token:state.token,uid:state.uid}});state.payload={...state.payload,...data};state.module=resolveModuleView(state.payload,state.locale);renderPayload()}catch(e){alert(e.message||t('genericError'))}finally{setActionBusy(button,false)}}
async function startModule(){const button=$('startModuleBtn');if(button?.getAttribute('aria-busy')==='true')return;if(!state.module?.startEnabled)return alert(t('modulePendingAlert'));setActionBusy(button,true);feedbackController?.startMonitoring({continuous:true});try{const key=state.payload?.runtime?.productKey;if(key==='cv_analysis')await cvModule.activate();else if(key==='video_presentation')await vpModule.activate();else if(key==='ai_literacy')await aiLiteracyModule.activate();else if(['assessment','snapshot'].includes(key))await assessmentModule.activate();else if(key==='interview')await interviewModule.activate();else throw new Error(t('modulePendingAlert'));button.dataset.activationCommitted='true'}catch(e){setActionBusy(button,false);alert(e.message||t('genericError'))}}
function wire(){
  $('langBtn').addEventListener('click',()=>{state.locale=state.locale===state.participantLocale?'en':state.participantLocale;applyLocale()});$('supportBtn').addEventListener('click',()=>{location.href='mailto:info@clarity-nvl.com'});$('continueProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('backWelcomeBtn').addEventListener('click',()=>{setStep('welcome');show('welcomeView')});$('saveProfileBtn').addEventListener('click',saveProfile);$('backProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('saveConsentBtn').addEventListener('click',saveConsent);$('statusBtn').addEventListener('click',refreshStatus);$('startModuleBtn').addEventListener('click',startModule);
  document.querySelectorAll('#consentView [data-legal-document]').forEach(button=>button.addEventListener('click',()=>openLegalDocument(button.dataset.legalDocument,button)));
  $('legalTabPrivacy').addEventListener('click',()=>renderLegalDocument('privacy'));
  $('legalTabParticipation').addEventListener('click',()=>renderLegalDocument('participation'));
  $('legalDialogCloseX').addEventListener('click',closeLegalDialog);
  $('legalDialogCloseBtn').addEventListener('click',closeLegalDialog);
  $('legalDialog').addEventListener('click',event=>{if(event.target===$('legalDialog'))closeLegalDialog()});
  $('legalDialog').addEventListener('close',()=>{const target=legalReturnFocus;legalReturnFocus=null;if(target&&typeof target.focus==='function')target.focus()});
}
cvModule=createCvModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});vpModule=createVideoPresentationModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail,refreshToken:refreshUniversalToken});aiLiteracyModule=createAiLiteracyModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});assessmentModule=createAssessmentModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail,refreshToken:refreshUniversalToken});interviewModule=createInterviewModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail,refreshToken:refreshUniversalToken});feedbackController=createAppFeedbackController({$,state,api,getLocale:()=>state.locale,getBrandingMode:()=>resolveBrandingMode(state.payload?.branding||state.payload?.runtime?.brandingSnapshot||{})});wire();applyLocale();bootstrap();
