import { resolveModuleView } from './modules/router-module.js';
import { createCvModule } from './modules/cv-module.js';
import { createVideoPresentationModule } from './modules/video-presentation-module.js';

const API_BASE = 'https://www.clarity-nvl.com/_functions';
const state = {
  uid: new URLSearchParams(location.search).get('uid') || '',
  token: '', payload: null, module: null, locale: 'en', step: 'welcome'
};
let cvModule = null;
let vpModule = null;

const $ = (id) => document.getElementById(id);
const TEXT = {
  de: {
    support:'Support', heroPrefix:'Willkommen bei', eyebrow:'Sicherer CLARITY-Zugang',
    loadingTitle:'Ihr CLARITY-Link wird geprüft…', loadingText:'Während der sicheren Prüfung werden keine Credits verbraucht.', loadingNotice:'Bitte lassen Sie dieses Fenster geöffnet.',
    workflow:'Workflow', mode:'Modus', language:'Sprache', purpose:'Position / Zweck', scope:'Umfang', accessId:'Zugangs-ID',
    accessSummary:'Zugangsübersicht', company:'Unternehmen', reportLang:'Reportsprache', units:'Reservierte Einheiten', status:'Status',
    welcome:'Ihr sicherer Workflow ist bereit', welcomeText:'Prüfen Sie die Angaben. Durch das Öffnen dieser Seite wurden keine Credits verbraucht.', continue:'Weiter',
    profile:'Teilnehmerprofil', profileText:'Bitte bestätigen Sie die Angaben, die für diesen Workflow verwendet werden.', firstName:'Vorname *', lastName:'Nachname *', email:'E-Mail *', reference:'Referenz (optional)', back:'Zurück', save:'Speichern und weiter',
    consent:'Datenschutz und Transparenz', consentText:'Bitte prüfen und bestätigen Sie die notwendigen Erklärungen, bevor das Produktmodul startet.', privacy:'Ich habe die Datenschutzhinweise gelesen und stimme der Verarbeitung meiner Daten für diesen CLARITY-Workflow zu.', ai:'Ich verstehe, dass KI den strukturierten Prozess unterstützt und endgültige Entscheidungen beim Menschen bleiben.', media:'Ich stimme der erforderlichen Mikrofon- oder Kameraverarbeitung für diesen Workflow zu.', confirm:'Bestätigen und weiter',
    productModule:'Produktmodul', moduleText:'Der Universal-App-Router hat die korrekte Produktkonfiguration geladen.', moduleNotice:'CV Analysis und Video Presentation sind als ausführbare Standalone-Module aktiviert. Weitere Produktmodule bleiben bis zu ihrer Vertical-Phase gesperrt.', refresh:'Status aktualisieren', start:'Workflow starten',
    unavailable:'Dieser CLARITY-Link ist nicht verfügbar', unavailableText:'Der Zugang konnte nicht sicher geprüft werden.', unavailableHelp:'Bitte wenden Sie sich an das Unternehmen, das Ihnen den Link gesendet hat.',
    step1:'1 · Willkommen', step1Text:'Zugang prüfen', step2:'2 · Profil', step2Text:'Teilnehmerangaben', step3:'3 · Einwilligung', step3Text:'Datenschutz und Transparenz', step4:'4 · Workflow', step4Text:'Produktmodul',
    noInfo:'Keine Angabe', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive Shell', routerReady:'Modul bereit', modulePending:'Produktmodul folgt', profileError:'Bitte füllen Sie Vorname, Nachname und eine gültige E-Mail-Adresse aus.', consentError:'Bitte bestätigen Sie alle erforderlichen Erklärungen.', genericError:'Der Vorgang konnte nicht abgeschlossen werden.', modulePendingAlert:'Dieses Produktmodul wird in einer folgenden Vertical-Phase aktiviert.'
  },
  en: {
    support:'Support', heroPrefix:'Welcome to', eyebrow:'Secure CLARITY access',
    loadingTitle:'Verifying your CLARITY link…', loadingText:'No credits are consumed while the secure access is checked.', loadingNotice:'Please keep this window open.',
    workflow:'Workflow', mode:'Mode', language:'Language', purpose:'Position / purpose', scope:'Scope', accessId:'Access ID',
    accessSummary:'Access summary', company:'Company', reportLang:'Report language', units:'Reserved units', status:'Status',
    welcome:'Your secure workflow is ready', welcomeText:'Review the information. Opening this page has not consumed any credits.', continue:'Continue',
    profile:'Participant profile', profileText:'Please confirm the details used for this workflow.', firstName:'First name *', lastName:'Last name *', email:'Email *', reference:'Reference (optional)', back:'Back', save:'Save and continue',
    consent:'Privacy and transparency', consentText:'Please review and confirm the required declarations before the product module starts.', privacy:'I have read the privacy information and agree that my data may be processed for this CLARITY workflow.', ai:'I understand that AI supports the structured process and that final decisions remain human-led.', media:'I agree to the required microphone or camera processing for this workflow.', confirm:'Confirm and continue',
    productModule:'Product module', moduleText:'The Universal App router has loaded the correct product configuration.', moduleNotice:'CV Analysis and Video Presentation are enabled as executable standalone modules. Other product modules remain locked until their vertical phase.', refresh:'Refresh status', start:'Start workflow',
    unavailable:'This CLARITY link is unavailable', unavailableText:'The access could not be verified securely.', unavailableHelp:'Please contact the organisation that sent you the link.',
    step1:'1 · Welcome', step1Text:'Access verification', step2:'2 · Profile', step2Text:'Participant details', step3:'3 · Consent', step3Text:'Privacy and transparency', step4:'4 · Workflow', step4Text:'Product module',
    noInfo:'Not specified', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive shell', routerReady:'Module ready', modulePending:'Product module pending', profileError:'Please enter first name, last name and a valid email address.', consentError:'Please confirm all required declarations.', genericError:'The operation could not be completed.', modulePendingAlert:'This product module is activated in a following vertical phase.'
  }
};

function t(key,...args){const value=TEXT[state.locale]?.[key]??TEXT.en[key]??key;return typeof value==='function'?value(...args):value}
function show(id){['loadingView','welcomeView','profileView','consentView','moduleView','cvView','cvProcessingView','cvCompleteView','vpView','vpProcessingView','vpCompleteView','errorView'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id))}
function setStep(step){state.step=step;const order=['welcome','profile','consent','module'];const pos=order.indexOf(step);document.querySelectorAll('.step').forEach((el,i)=>{el.classList.toggle('active',i===pos);el.classList.toggle('done',i<pos)})}
function langName(code){return({de:'Deutsch',en:'English',fr:'Français',es:'Español',it:'Italiano',nl:'Nederlands',pt:'Português',pl:'Polski',tr:'Türkçe',ar:'العربية'})[code]||String(code||'—').toUpperCase()}
function modeName(mode){const map={audio:'Audio',video:'Video',mix:'Mix',audio_chat:'Audio + Chat',video_chat:'Video + Chat',chat:'Chat',upload:'Upload',standard:'Standard'};return map[mode]||String(mode||'—').replaceAll('_',' ')}
function applyLocale(){
  document.documentElement.lang=state.locale;$('langBtn').textContent=state.locale==='de'?'EN':'DE';
  const map={eyebrow:'eyebrow',heroPrefix:'heroPrefix',loadingTitle:'loadingTitle',loadingText:'loadingText',loadingNotice:'loadingNotice',metaWorkflowLabel:'workflow',metaModeLabel:'mode',metaLanguageLabel:'language',metaPurposeLabel:'purpose',metaQuestionsLabel:'scope',metaUidLabel:'accessId',summaryTitle:'accessSummary',summaryCompanyLabel:'company',summaryReportLabel:'reportLang',summaryUnitsLabel:'units',summaryStatusLabel:'status',welcomeTitle:'welcome',welcomeText:'welcomeText',continueProfileBtn:'continue',profileTitle:'profile',profileText:'profileText',firstNameLabel:'firstName',lastNameLabel:'lastName',emailLabel:'email',referenceLabel:'reference',backWelcomeBtn:'back',saveProfileBtn:'save',consentTitle:'consent',consentText:'consentText',privacyConsentText:'privacy',aiConsentText:'ai',mediaConsentText:'media',backProfileBtn:'back',saveConsentBtn:'confirm',moduleViewTitle:'productModule',moduleViewText:'moduleText',moduleNotice:'moduleNotice',statusBtn:'refresh',startModuleBtn:'start',errorTitle:'unavailable',errorText:'unavailableText',errorHelp:'unavailableHelp',step1Title:'step1',step1Text:'step1Text',step2Title:'step2',step2Text:'step2Text',step3Title:'step3',step3Text:'step3Text',step4Title:'step4',step4Text:'step4Text'};
  Object.entries(map).forEach(([id,k])=>{if($(id))$(id).textContent=t(k)});renderPayload();cvModule?.applyLocale();vpModule?.applyLocale();
}
function normalizeWixImageUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw))return raw;if(/^wix:image:\/\//i.test(raw)){const match=raw.match(/^wix:image:\/\/v1\/([^/]+)\//i)||raw.match(/^wix:image:\/\/([^/]+)\//i);return match?.[1]?`https://static.wixstatic.com/media/${encodeURIComponent(match[1])}`:''}return''}
function assetCandidates(value){if(!value)return[];if(typeof value==='string')return[value];if(typeof value!=='object'||Array.isArray(value))return[];return[value.publicUrl,value.logoPublicUrl,value.previewUrl,value.logoPreviewUrl,value.fileUrl,value.logoFileUrl,value.downloadUrl,value.src,value.url,value.assetUrl,value.mediaUrl]}
function resolveBrandLogoSource(branding={}){const values=[branding.logoUrl,branding.logoPublicUrl,branding.publicLogoUrl,branding.customerLogo,branding.logo,branding.logoAsset,branding.media,branding.metadata?.logoPublicUrl,branding.metadata?.logoFileUrl];for(const value of values){for(const candidate of assetCandidates(value)){const url=normalizeWixImageUrl(candidate);if(url)return url}}return''}
function preloadImage(url,timeoutMs=8000){return new Promise((resolve,reject)=>{if(!url)return reject(Object.assign(new Error('Brand logo URL missing.'),{code:'BRAND_LOGO_URL_MISSING'}));const image=new Image();let done=false;const finish=(fn,value)=>{if(done)return;done=true;clearTimeout(timer);fn(value)};const timer=setTimeout(()=>finish(reject,Object.assign(new Error('Brand logo preload timed out.'),{code:'BRAND_LOGO_PRELOAD_TIMEOUT'})),timeoutMs);image.onload=()=>finish(resolve,url);image.onerror=()=>finish(reject,Object.assign(new Error('Brand logo could not be loaded.'),{code:'BRAND_LOGO_LOAD_FAILED',details:{url}}));image.referrerPolicy='no-referrer';image.src=url})}
function revealApp(){document.body.classList.remove('branding-pending');document.body.classList.add('branding-ready');$('appShell')?.setAttribute('aria-hidden','false');$('bootstrapGate')?.classList.add('ready');$('bootstrapGate')?.setAttribute('aria-busy','false')}
async function applyBranding(branding={}){const colors=branding.colors||{},root=document.documentElement,mode=String(branding.brandingMode||'clarity').toLowerCase().replace(/[\s-]+/g,'_'),white=mode==='white_label';if(colors.primary)root.style.setProperty('--navy',colors.primary);if(colors.accent)root.style.setProperty('--cyan',colors.accent);if(colors.secondary)root.style.setProperty('--violet',colors.secondary);if(colors.highlight||colors.magenta)root.style.setProperty('--magenta',colors.highlight||colors.magenta);$('brandName').textContent=branding.brandName||(white?'':'CLARITY');$('productLine').textContent=white?(branding.candidatePageSettings?.productLine||'Decision Intelligence Platform'):(branding.legalProductName||'CLARITY Decision Intelligence Platform');const logo=resolveBrandLogoSource(branding);const logoEl=$('brandLogo');logoEl.hidden=true;logoEl.removeAttribute('src');logoEl.style.visibility='visible';let appliedLogo='';if(logo){try{await preloadImage(logo);appliedLogo=logo}catch(error){console.warn('[CLARITY APP] Branding asset fallback',error)}}if(!appliedLogo&&!white){try{await preloadImage('./assets/clarity-logo.png');appliedLogo='./assets/clarity-logo.png'}catch(_){}}if(appliedLogo){logoEl.src=appliedLogo;logoEl.alt=`${branding.brandName||'CLARITY'} logo`;logoEl.hidden=false;const favicon=$('appFavicon');if(favicon)favicon.href=appliedLogo}else{logoEl.hidden=true}return{mode,whiteLabel:white,logoUrl:appliedLogo,assetFallback:Boolean(logo&&!appliedLogo)}}
function renderPayload(){
  if(!state.payload)return;const r=state.payload.runtime||{},b=state.payload.branding||{},m=state.module||resolveModuleView(state.payload,state.locale);state.module=m;
  const brandMode=String(b.brandingMode||'clarity').toLowerCase().replace(/[\s-]+/g,'_');const whiteLabel=brandMode==='white_label';const moduleTitle=m.title||'CLARITY';$('heroProduct').textContent=whiteLabel?`${b.brandName||'Company'} ${moduleTitle.replace(/^CLARITY\s*/i,'')}`:moduleTitle;$('heroDescription').textContent=m.description||'';$('moduleIcon').textContent=m.icon||'CL';$('finalModuleIcon').textContent=m.icon||'CL';$('moduleTitle').textContent=m.title||'CLARITY';$('moduleDescription').textContent=m.description||'';$('finalModuleTitle').textContent=m.title||'CLARITY';$('finalModuleDescription').textContent=m.description||'';
  $('metaWorkflow').textContent=r.workflowKey||'—';$('metaMode').textContent=modeName(r.mode);$('metaLanguage').textContent=langName(r.participantLang);$('metaPurpose').textContent=r.position||r.purpose||t('noInfo');$('metaQuestions').textContent=t('questions',r.questionCount);$('metaUid').textContent=r.uid||'—';
  $('summaryCompany').textContent=b.brandName||b.companyId||'CLARITY';$('summaryReport').textContent=langName(r.reportLang);$('summaryUnits').textContent=String(r.requiredUnits??0);$('summaryStatus').textContent=r.status||'—';
  $('moduleReadiness').textContent=m.startEnabled?t('routerReady'):t('modulePending');$('moduleDevice').textContent=t('responsive');$('finalWorkflow').textContent=r.workflowKey||'—';$('finalStatus').textContent=m.readiness||'—';$('startModuleBtn').disabled=!m.startEnabled;$('mediaConsentRow').classList.toggle('hidden',!m.media);applyBranding(b);
}
async function api(path,{method='POST',body=null,query={}}={}){const url=new URL(`${API_BASE}/${path}`);Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,v)});const response=await fetch(url,{method,headers:{'Content-Type':'application/json','Accept':'application/json'},body:body?JSON.stringify(body):undefined,credentials:'omit',cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok||data?.ok===false){const errorPayload=typeof data?.error==='object'?data.error:{};const e=new Error(errorPayload.message||data?.message||`HTTP ${response.status}`);e.code=errorPayload.code||data?.code||data?.error||`HTTP_${response.status}`;e.details=errorPayload.details||data?.details||null;throw e}return data}
function deviceClass(){const w=Math.min(screen.width||innerWidth,innerWidth);return w<600?'mobile':w<1024?'tablet':'desktop'}
function prefill(){const p=state.payload?.runtime?.candidateProfile||{};$('firstName').value=p.firstName||'';$('lastName').value=p.lastName||'';$('email').value=p.email||'';$('externalReference').value=p.externalReference||''}
async function fail(error){try{await applyBranding({brandingMode:'clarity',brandName:'CLARITY',legalProductName:'CLARITY Decision Intelligence Platform',logoUrl:'./assets/clarity-logo.png'})}catch(_){}revealApp();show('errorView');$('errorText').textContent=error?.message||t('unavailableText');$('errorCode').textContent=error?.code||'UNIVERSAL_APP_ERROR'}
async function bootstrap(){if(!state.uid)return fail({code:'UNIVERSAL_UID_REQUIRED',message:t('unavailableText')});try{const data=await api('v2AppBootstrap',{method:'GET',query:{uid:state.uid,userAgent:navigator.userAgent,deviceClass:deviceClass()}});state.payload=data;state.token=data.token||'';state.locale=data.runtime?.participantLang==='de'?'de':'en';state.module=resolveModuleView(data,state.locale);prefill();applyLocale();await applyBranding(data.branding||data.runtime?.brandingSnapshot||{});setStep('welcome');show('welcomeView');revealApp()}catch(e){await fail(e)}}
async function saveProfile(){const profile={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),email:$('email').value.trim(),externalReference:$('externalReference').value.trim()};if(!profile.firstName||!profile.lastName||!/^\S+@\S+\.\S+$/.test(profile.email))return alert(t('profileError'));$('saveProfileBtn').disabled=true;try{const data=await api('v2AppProfile',{body:{token:state.token,uid:state.uid,profile}});state.payload.runtime={...state.payload.runtime,...data.runtime};setStep('consent');show('consentView')}catch(e){alert(e.message||t('genericError'))}finally{$('saveProfileBtn').disabled=false}}
async function saveConsent(){const mediaOk=!state.module?.media||$('mediaConsent').checked;if(!$('privacyConsent').checked||!$('aiConsent').checked||!mediaOk)return alert(t('consentError'));$('saveConsentBtn').disabled=true;try{const data=await api('v2AppConsent',{body:{token:state.token,uid:state.uid,accepted:true,privacyAccepted:true,aiInteractionAccepted:true,mediaAccepted:state.module?.media===true,version:'universal-consent-v1'}});state.payload.runtime={...state.payload.runtime,...data.runtime};renderPayload();setStep('module');show('moduleView')}catch(e){alert(e.message||t('genericError'))}finally{$('saveConsentBtn').disabled=false}}
async function refreshStatus(){try{const data=await api('v2AppStatus',{body:{token:state.token,uid:state.uid}});state.payload={...state.payload,...data};state.module=resolveModuleView(state.payload,state.locale);renderPayload()}catch(e){alert(e.message||t('genericError'))}}
async function startModule(){if(!state.module?.startEnabled)return alert(t('modulePendingAlert'));if(state.payload?.runtime?.productKey==='cv_analysis')return cvModule.activate();if(state.payload?.runtime?.productKey==='video_presentation')return vpModule.activate();alert(t('modulePendingAlert'))}
function wire(){
  $('langBtn').addEventListener('click',()=>{state.locale=state.locale==='de'?'en':'de';applyLocale()});$('supportBtn').addEventListener('click',()=>{location.href='mailto:info@clarity-nvl.com'});$('continueProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('backWelcomeBtn').addEventListener('click',()=>{setStep('welcome');show('welcomeView')});$('saveProfileBtn').addEventListener('click',saveProfile);$('backProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('saveConsentBtn').addEventListener('click',saveConsent);$('statusBtn').addEventListener('click',refreshStatus);$('startModuleBtn').addEventListener('click',startModule);
}
cvModule=createCvModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});vpModule=createVideoPresentationModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});wire();applyLocale();bootstrap();
