import { resolveModuleView } from './modules/router-module.js';
import { createCvModule } from './modules/cv-module.js';
import { createVideoPresentationModule } from './modules/video-presentation-module.js';
import { createAiLiteracyModule } from './modules/ai-literacy-module.js?v=2.16.1-ail-certificate-recovery';
import { createAssessmentModule } from './modules/assessment-module.js?v=2.27.1-e2-5-assessment-media-language-recovery';
import { createInterviewModule } from './modules/interview-module.js?v=1.10.1-q10-start-closeout-recovery';

const API_BASE = 'https://www.clarity-nvl.com/_functions';
const state = {
  uid: new URLSearchParams(location.search).get('uid') || '',
  token: '', payload: null, module: null, locale: 'en', participantLocale: 'en', step: 'welcome'
};
let cvModule = null;
let vpModule = null;
let aiLiteracyModule = null;
let assessmentModule = null;
let interviewModule = null;
let tokenRefreshPromise = null;
const SUPPORT_DIAGNOSTICS = new URLSearchParams(location.search).get('supportDebug') === '1';

const $ = (id) => document.getElementById(id);
const TEXT = {
  de: {
    support:'Support', heroPrefix:'Willkommen bei', eyebrow:'Sicherer CLARITY-Zugang',
    loadingTitle:'Ihr CLARITY-Link wird geprüft…', loadingText:'Während der sicheren Prüfung werden keine Credits verbraucht.', loadingNotice:'Bitte lassen Sie dieses Fenster geöffnet.',
    workflow:'Workflow', mode:'Modus', language:'Sprache', purpose:'Position / Zweck', scope:'Umfang', accessId:'Zugangs-ID',
    accessSummary:'Zugangsübersicht', company:'Unternehmen', reportLang:'Reportsprache', units:'Reservierte Einheiten', status:'Status',
    welcome:'Ihr sicherer Workflow ist bereit', welcomeText:'Prüfen Sie die Angaben. Durch das Öffnen dieser Seite wurden keine Credits verbraucht.', continue:'Weiter',
    profile:'Teilnehmerprofil', profileText:'Bitte bestätigen Sie die Angaben, die für diesen Workflow verwendet werden.', firstName:'Vorname *', lastName:'Nachname *', email:'E-Mail *', reference:'Referenz (optional)', back:'Zurück', save:'Speichern und weiter',
    consent:'Datenschutz und Transparenz', consentText:'Bitte prüfen und bestätigen Sie die notwendigen Erklärungen, bevor das Produktmodul startet.', privacy:'Ich habe die Datenschutzhinweise gelesen und stimme der Verarbeitung meiner Daten für diesen CLARITY-Workflow zu.', ai:'Ich verstehe, dass KI den strukturierten Prozess unterstützt und endgültige Entscheidungen beim Menschen bleiben.', media:'Ich stimme der erforderlichen Mikrofon- oder Kameraverarbeitung für diesen Workflow zu.', confirm:'Bestätigen und weiter',
    productModule:'Produktmodul', moduleText:'Der Universal-App-Router hat die korrekte Produktkonfiguration geladen.', moduleNotice:'Ihr Interview ist vorbereitet. Öffnen Sie das Interview, prüfen Sie Ihr Gerät und starten Sie anschließend.', refresh:'Status aktualisieren', start:'Workflow starten',
    unavailable:'Dieser CLARITY-Link ist nicht verfügbar', unavailableText:'Der Zugang konnte nicht sicher geprüft werden.', unavailableHelp:'Bitte wenden Sie sich an das Unternehmen, das Ihnen den Link gesendet hat.',
    step1:'1 · Willkommen', step1Text:'Zugang prüfen', step2:'2 · Profil', step2Text:'Teilnehmerangaben', step3:'3 · Einwilligung', step3Text:'Datenschutz und Transparenz', step4:'4 · Workflow', step4Text:'Produktmodul',
    noInfo:'Keine Angabe', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive Shell', routerReady:'Modul bereit', modulePending:'Produktmodul folgt', profileError:'Bitte füllen Sie Vorname, Nachname und eine gültige E-Mail-Adresse aus.', consentError:'Bitte bestätigen Sie alle erforderlichen Erklärungen.', genericError:'Der Vorgang konnte nicht abgeschlossen werden.', modulePendingAlert:'Dieses Produktmodul wird in einer folgenden Vertical-Phase aktiviert.', interviewReady:'Das Interview ist bereit.', interviewOpenNotice:'Öffnen Sie das Interview, prüfen Sie Kamera beziehungsweise Mikrofon und starten Sie anschließend.', openInterview:'Interview öffnen'
  },
  en: {
    support:'Support', heroPrefix:'Welcome to', eyebrow:'Secure CLARITY access',
    loadingTitle:'Verifying your CLARITY link…', loadingText:'No credits are consumed while the secure access is checked.', loadingNotice:'Please keep this window open.',
    workflow:'Workflow', mode:'Mode', language:'Language', purpose:'Position / purpose', scope:'Scope', accessId:'Access ID',
    accessSummary:'Access summary', company:'Company', reportLang:'Report language', units:'Reserved units', status:'Status',
    welcome:'Your secure workflow is ready', welcomeText:'Review the information. Opening this page has not consumed any credits.', continue:'Continue',
    profile:'Participant profile', profileText:'Please confirm the details used for this workflow.', firstName:'First name *', lastName:'Last name *', email:'Email *', reference:'Reference (optional)', back:'Back', save:'Save and continue',
    consent:'Privacy and transparency', consentText:'Please review and confirm the required declarations before the product module starts.', privacy:'I have read the privacy information and agree that my data may be processed for this CLARITY workflow.', ai:'I understand that AI supports the structured process and that final decisions remain human-led.', media:'I agree to the required microphone or camera processing for this workflow.', confirm:'Confirm and continue',
    productModule:'Product module', moduleText:'The Universal App router has loaded the correct product configuration.', moduleNotice:'Your Interview is ready. Open it, check your device once, and then start.', refresh:'Refresh status', start:'Start workflow',
    unavailable:'This CLARITY link is unavailable', unavailableText:'The access could not be verified securely.', unavailableHelp:'Please contact the organisation that sent you the link.',
    step1:'1 · Welcome', step1Text:'Access verification', step2:'2 · Profile', step2Text:'Participant details', step3:'3 · Consent', step3Text:'Privacy and transparency', step4:'4 · Workflow', step4Text:'Product module',
    noInfo:'Not specified', questions:(n)=>n?`Q${n}`:'Standard', responsive:'Responsive shell', routerReady:'Module ready', modulePending:'Product module pending', profileError:'Please enter first name, last name and a valid email address.', consentError:'Please confirm all required declarations.', genericError:'The operation could not be completed.', modulePendingAlert:'This product module is activated in a following vertical phase.', interviewReady:'The Interview is ready.', interviewOpenNotice:'Open the Interview, check your camera or microphone once, and then start.', openInterview:'Open Interview'
  }
};

const LANGUAGE_OVERRIDES={
  es:{eyebrow:'Acceso seguro',loadingTitle:'Verificando su enlace…',loadingText:'No se consume ningún crédito durante la verificación.',loadingNotice:'Mantenga esta ventana abierta.',welcome:'Su flujo seguro está listo',welcomeText:'Revise la información. Abrir esta página no ha consumido créditos.',continue:'Continuar',profile:'Perfil del participante',profileText:'Confirme los datos utilizados para este flujo.',firstName:'Nombre *',lastName:'Apellidos *',reference:'Referencia (opcional)',back:'Atrás',save:'Guardar y continuar',consent:'Privacidad y transparencia',consentText:'Revise y confirme las declaraciones necesarias antes de iniciar el módulo.',confirm:'Confirmar y continuar',start:'Iniciar flujo',unavailable:'Este enlace no está disponible',unavailableText:'No se ha podido verificar el acceso de forma segura.',interviewReady:'La entrevista está lista.',interviewOpenNotice:'Abra la entrevista, compruebe la cámara o el micrófono y comience.',openInterview:'Abrir entrevista'},
  fr:{eyebrow:'Accès sécurisé',loadingTitle:'Vérification de votre lien…',loadingText:'Aucun crédit n’est consommé pendant la vérification.',loadingNotice:'Veuillez garder cette fenêtre ouverte.',welcome:'Votre parcours sécurisé est prêt',welcomeText:'Vérifiez les informations. L’ouverture de cette page n’a consommé aucun crédit.',continue:'Continuer',profile:'Profil du participant',profileText:'Veuillez confirmer les informations utilisées pour ce parcours.',firstName:'Prénom *',lastName:'Nom *',reference:'Référence (facultatif)',back:'Retour',save:'Enregistrer et continuer',consent:'Confidentialité et transparence',consentText:'Veuillez vérifier et confirmer les déclarations requises avant le démarrage du module.',confirm:'Confirmer et continuer',start:'Démarrer',unavailable:'Ce lien n’est pas disponible',unavailableText:'L’accès n’a pas pu être vérifié de manière sécurisée.',interviewReady:'L’entretien est prêt.',interviewOpenNotice:'Ouvrez l’entretien, vérifiez la caméra ou le microphone, puis démarrez.',openInterview:'Ouvrir l’entretien'},
  it:{eyebrow:'Accesso sicuro',loadingTitle:'Verifica del collegamento…',loadingText:'Durante la verifica non viene consumato alcun credito.',loadingNotice:'Mantenga aperta questa finestra.',welcome:'Il flusso sicuro è pronto',welcomeText:'Controlli le informazioni. L’apertura della pagina non ha consumato crediti.',continue:'Continua',profile:'Profilo del partecipante',profileText:'Confermi i dati utilizzati per questo flusso.',firstName:'Nome *',lastName:'Cognome *',reference:'Riferimento (facoltativo)',back:'Indietro',save:'Salva e continua',consent:'Privacy e trasparenza',consentText:'Controlli e confermi le dichiarazioni richieste prima dell’avvio del modulo.',confirm:'Conferma e continua',start:'Avvia flusso',unavailable:'Questo collegamento non è disponibile',unavailableText:'Non è stato possibile verificare l’accesso in modo sicuro.',interviewReady:'L’intervista è pronta.',interviewOpenNotice:'Apra l’intervista, controlli videocamera o microfono e inizi.',openInterview:'Apri intervista'},
  pt:{eyebrow:'Acesso seguro',loadingTitle:'A verificar a ligação…',loadingText:'Nenhum crédito é consumido durante a verificação.',loadingNotice:'Mantenha esta janela aberta.',welcome:'O seu fluxo seguro está pronto',welcomeText:'Reveja as informações. Abrir esta página não consumiu créditos.',continue:'Continuar',profile:'Perfil do participante',profileText:'Confirme os dados utilizados neste fluxo.',firstName:'Nome *',lastName:'Apelido *',reference:'Referência (opcional)',back:'Voltar',save:'Guardar e continuar',consent:'Privacidade e transparência',consentText:'Reveja e confirme as declarações necessárias antes do início do módulo.',confirm:'Confirmar e continuar',start:'Iniciar fluxo',unavailable:'Esta ligação não está disponível',unavailableText:'Não foi possível verificar o acesso com segurança.',interviewReady:'A entrevista está pronta.',interviewOpenNotice:'Abra a entrevista, verifique a câmara ou o microfone e inicie.',openInterview:'Abrir entrevista'},
  nl:{eyebrow:'Beveiligde toegang',loadingTitle:'Uw link wordt gecontroleerd…',loadingText:'Tijdens de controle worden geen credits verbruikt.',loadingNotice:'Laat dit venster open.',welcome:'Uw beveiligde workflow is klaar',welcomeText:'Controleer de informatie. Het openen van deze pagina heeft geen credits verbruikt.',continue:'Doorgaan',profile:'Deelnemersprofiel',profileText:'Bevestig de gegevens voor deze workflow.',firstName:'Voornaam *',lastName:'Achternaam *',reference:'Referentie (optioneel)',back:'Terug',save:'Opslaan en doorgaan',consent:'Privacy en transparantie',consentText:'Controleer en bevestig de vereiste verklaringen voordat de module start.',confirm:'Bevestigen en doorgaan',start:'Workflow starten',unavailable:'Deze link is niet beschikbaar',unavailableText:'De toegang kon niet veilig worden gecontroleerd.',interviewReady:'Het interview is klaar.',interviewOpenNotice:'Open het interview, controleer camera of microfoon en start daarna.',openInterview:'Interview openen'},
  pl:{eyebrow:'Bezpieczny dostęp',loadingTitle:'Sprawdzanie łącza…',loadingText:'Podczas weryfikacji nie są zużywane żadne kredyty.',loadingNotice:'Pozostaw to okno otwarte.',welcome:'Bezpieczny proces jest gotowy',welcomeText:'Sprawdź informacje. Otwarcie tej strony nie zużyło kredytów.',continue:'Kontynuuj',profile:'Profil uczestnika',profileText:'Potwierdź dane używane w tym procesie.',firstName:'Imię *',lastName:'Nazwisko *',reference:'Referencja (opcjonalnie)',back:'Wstecz',save:'Zapisz i kontynuuj',consent:'Prywatność i przejrzystość',consentText:'Przejrzyj i potwierdź wymagane oświadczenia przed uruchomieniem modułu.',confirm:'Potwierdź i kontynuuj',start:'Uruchom proces',unavailable:'To łącze jest niedostępne',unavailableText:'Nie udało się bezpiecznie zweryfikować dostępu.',interviewReady:'Rozmowa jest gotowa.',interviewOpenNotice:'Otwórz rozmowę, sprawdź kamerę lub mikrofon, a następnie rozpocznij.',openInterview:'Otwórz rozmowę'},
  tr:{eyebrow:'Güvenli erişim',loadingTitle:'Bağlantınız doğrulanıyor…',loadingText:'Doğrulama sırasında kredi kullanılmaz.',loadingNotice:'Lütfen bu pencereyi açık tutun.',welcome:'Güvenli iş akışınız hazır',welcomeText:'Bilgileri kontrol edin. Bu sayfayı açmak kredi tüketmedi.',continue:'Devam',profile:'Katılımcı profili',profileText:'Bu iş akışında kullanılan bilgileri onaylayın.',firstName:'Ad *',lastName:'Soyad *',reference:'Referans (isteğe bağlı)',back:'Geri',save:'Kaydet ve devam et',consent:'Gizlilik ve şeffaflık',consentText:'Modül başlamadan önce gerekli beyanları inceleyip onaylayın.',confirm:'Onayla ve devam et',start:'İş akışını başlat',unavailable:'Bu bağlantı kullanılamıyor',unavailableText:'Erişim güvenli biçimde doğrulanamadı.',interviewReady:'Mülakat hazır.',interviewOpenNotice:'Mülakatı açın, kamerayı veya mikrofonu kontrol edin ve başlayın.',openInterview:'Mülakatı aç'},
  ar:{eyebrow:'وصول آمن',loadingTitle:'جارٍ التحقق من الرابط…',loadingText:'لا يتم استهلاك أي رصيد أثناء التحقق.',loadingNotice:'يرجى إبقاء هذه النافذة مفتوحة.',welcome:'سير العمل الآمن جاهز',welcomeText:'راجع المعلومات. لم يؤد فتح هذه الصفحة إلى استهلاك أي رصيد.',continue:'متابعة',profile:'ملف المشارك',profileText:'يرجى تأكيد البيانات المستخدمة في سير العمل.',firstName:'الاسم الأول *',lastName:'اسم العائلة *',reference:'المرجع (اختياري)',back:'رجوع',save:'حفظ ومتابعة',consent:'الخصوصية والشفافية',consentText:'يرجى مراجعة الإقرارات المطلوبة وتأكيدها قبل بدء الوحدة.',confirm:'تأكيد ومتابعة',start:'بدء سير العمل',unavailable:'هذا الرابط غير متاح',unavailableText:'تعذر التحقق من الوصول بأمان.',interviewReady:'المقابلة جاهزة.',interviewOpenNotice:'افتح المقابلة وتحقق من الكاميرا أو الميكروفون ثم ابدأ.',openInterview:'فتح المقابلة'}
};
Object.entries(LANGUAGE_OVERRIDES).forEach(([code,copy])=>{TEXT[code]={...TEXT.en,...copy}});
function normalizeUiLocale(value='en'){const code=String(value||'en').toLowerCase().split(/[-_]/)[0];return TEXT[code]?code:'en'}

function t(key,...args){const value=TEXT[state.locale]?.[key]??TEXT.en[key]??key;return typeof value==='function'?value(...args):value}
function show(id){['loadingView','welcomeView','profileView','consentView','moduleView','assessmentView','cvView','cvProcessingView','cvCompleteView','vpView','vpProcessingView','vpCompleteView','aiLiteracyView','errorView'].forEach(x=>$(x)?.classList.toggle('hidden',x!==id))}
function setStep(step){state.step=step;const order=['welcome','profile','consent','module'];const pos=order.indexOf(step);document.querySelectorAll('.step').forEach((el,i)=>{el.classList.toggle('active',i===pos);el.classList.toggle('done',i<pos)})}
function langName(code){return({de:'Deutsch',en:'English',fr:'Français',es:'Español',it:'Italiano',nl:'Nederlands',pt:'Português',pl:'Polski',tr:'Türkçe',ar:'العربية'})[code]||String(code||'—').toUpperCase()}
function modeName(mode){const map={audio:'Audio',video:'Video',mix:'Mix',audio_chat:'Audio + Chat',video_chat:'Video + Chat',chat:'Chat',upload:'Upload',standard:'Standard'};return map[mode]||String(mode||'—').replaceAll('_',' ')}
function applyLocale(){
  document.documentElement.lang=state.locale;document.documentElement.dir=state.locale==='ar'?'rtl':'ltr';$('langBtn').textContent=state.locale===state.participantLocale?'EN':state.participantLocale.toUpperCase();
  const map={eyebrow:'eyebrow',heroPrefix:'heroPrefix',loadingTitle:'loadingTitle',loadingText:'loadingText',loadingNotice:'loadingNotice',metaWorkflowLabel:'workflow',metaModeLabel:'mode',metaLanguageLabel:'language',metaPurposeLabel:'purpose',metaQuestionsLabel:'scope',metaUidLabel:'accessId',summaryTitle:'accessSummary',summaryCompanyLabel:'company',summaryReportLabel:'reportLang',summaryUnitsLabel:'units',summaryStatusLabel:'status',welcomeTitle:'welcome',welcomeText:'welcomeText',continueProfileBtn:'continue',profileTitle:'profile',profileText:'profileText',firstNameLabel:'firstName',lastNameLabel:'lastName',emailLabel:'email',referenceLabel:'reference',backWelcomeBtn:'back',saveProfileBtn:'save',consentTitle:'consent',consentText:'consentText',privacyConsentText:'privacy',aiConsentText:'ai',mediaConsentText:'media',backProfileBtn:'back',saveConsentBtn:'confirm',moduleViewTitle:'productModule',moduleViewText:'moduleText',moduleNotice:'moduleNotice',statusBtn:'refresh',startModuleBtn:'start',errorTitle:'unavailable',errorText:'unavailableText',errorHelp:'unavailableHelp',step1Title:'step1',step1Text:'step1Text',step2Title:'step2',step2Text:'step2Text',step3Title:'step3',step3Text:'step3Text',step4Title:'step4',step4Text:'step4Text'};
  Object.entries(map).forEach(([id,k])=>{if($(id))$(id).textContent=t(k)});renderPayload();cvModule?.applyLocale();vpModule?.applyLocale();aiLiteracyModule?.applyLocale();assessmentModule?.applyLocale();
}
function normalizeWixImageUrl(value){const raw=String(value||'').trim();if(!raw)return'';if(/^https?:\/\//i.test(raw))return raw;if(/^wix:image:\/\//i.test(raw)){const match=raw.match(/^wix:image:\/\/v1\/([^/]+)\//i)||raw.match(/^wix:image:\/\/([^/]+)\//i);return match?.[1]?`https://static.wixstatic.com/media/${encodeURIComponent(match[1])}`:''}return''}
function normalizeBrandingMode(value){const raw=String(value||'clarity').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');if(['co_branding','cobranding','co_branded','cobranded','customer','recruitment'].includes(raw))return'cobranded';if(['white_label','whitelabel','white_branded'].includes(raw))return'whitelabel';return'clarity'}
function assetCandidates(value){if(!value)return[];if(typeof value==='string')return[value];if(typeof value!=='object'||Array.isArray(value))return[];return[value.publicUrl,value.logoPublicUrl,value.previewUrl,value.logoPreviewUrl,value.fileUrl,value.logoFileUrl,value.downloadUrl,value.src,value.url,value.assetUrl,value.mediaUrl]}
function resolveBrandLogoSource(branding={},mode='clarity'){const explicitCustomer=[branding.customerLogoUrl,branding.companyLogoUrl,branding.customerLogo,branding.companyLogo,branding.customerLogoCandidates,branding.metadata?.customerLogoUrl,branding.metadata?.companyLogoUrl];const generic=[branding.logoUrl,branding.logoPublicUrl,branding.publicLogoUrl,branding.primaryLogo,branding.logo,branding.logoAsset,branding.media,branding.metadata?.logoPublicUrl,branding.metadata?.logoFileUrl];const values=mode==='whitelabel'?explicitCustomer:[...explicitCustomer,...generic];for(const value of values){const items=Array.isArray(value)?value:[value];for(const item of items){for(const candidate of assetCandidates(item)){const url=normalizeWixImageUrl(candidate);if(url)return url}}}return''}
function preloadImage(url,timeoutMs=8000){return new Promise((resolve,reject)=>{if(!url)return reject(Object.assign(new Error('Brand logo URL missing.'),{code:'BRAND_LOGO_URL_MISSING'}));const image=new Image();let done=false;const finish=(fn,value)=>{if(done)return;done=true;clearTimeout(timer);fn(value)};const timer=setTimeout(()=>finish(reject,Object.assign(new Error('Brand logo preload timed out.'),{code:'BRAND_LOGO_PRELOAD_TIMEOUT'})),timeoutMs);image.onload=()=>finish(resolve,url);image.onerror=()=>finish(reject,Object.assign(new Error('Brand logo could not be loaded.'),{code:'BRAND_LOGO_LOAD_FAILED',details:{url}}));image.referrerPolicy='no-referrer';image.src=url})}
function revealApp(){document.body.classList.remove('branding-pending');document.body.classList.add('branding-ready');$('appShell')?.setAttribute('aria-hidden','false');$('bootstrapGate')?.classList.add('ready');$('bootstrapGate')?.setAttribute('aria-busy','false')}
async function applyBranding(branding={}){const colors=branding.colors||{},root=document.documentElement,mode=normalizeBrandingMode(branding.brandingMode||branding.mode),white=mode==='whitelabel',co=mode==='cobranded';if(colors.primary)root.style.setProperty('--navy',colors.primary);if(colors.accent)root.style.setProperty('--cyan',colors.accent);if(colors.secondary)root.style.setProperty('--violet',colors.secondary);if(colors.highlight||colors.magenta)root.style.setProperty('--magenta',colors.highlight||colors.magenta);const customerName=branding.reportBrandName||branding.brandName||branding.companyName||'Company';$('brandName').textContent=white||co?customerName:'CLARITY';$('productLine').textContent=white?(branding.candidatePageSettings?.productLine||branding.productLine||''):(co?(branding.poweredByClarityVisible===false?'':'Powered by CLARITY'):(branding.legalProductName||'CLARITY Decision Intelligence Platform'));const logo=resolveBrandLogoSource(branding,mode);const logoEl=$('brandLogo');logoEl.hidden=true;logoEl.removeAttribute('src');logoEl.style.visibility='visible';let appliedLogo='';if(logo&&branding.customerLogoVisible!==false){try{await preloadImage(logo);appliedLogo=logo}catch(error){SUPPORT_DIAGNOSTICS&&console.warn('[CLARITY APP] Branding asset fallback',error)}}if(!appliedLogo&&!white){try{await preloadImage('./assets/clarity-logo.png');appliedLogo='./assets/clarity-logo.png'}catch(_){}}if(appliedLogo){logoEl.src=appliedLogo;logoEl.alt=`${white||co?customerName:'CLARITY'} logo`;logoEl.hidden=false;const favicon=$('appFavicon');if(favicon)favicon.href=appliedLogo}else{logoEl.hidden=true}const footer=$('footerLeft');if(footer)footer.textContent=white?(branding.footerBrandName||customerName):(co?`${customerName}${branding.poweredByClarityVisible===false?'':' · Powered by CLARITY'}`:'CLARITY Decision Intelligence Platform');return{mode,whiteLabel:white,coBranding:co,logoUrl:appliedLogo,assetFallback:Boolean(logo&&!appliedLogo)}}
function renderPayload(){
  if(!state.payload)return;const r=state.payload.runtime||{},b=state.payload.branding||{},m=state.module||resolveModuleView(state.payload,state.locale);state.module=m;
  const brandMode=normalizeBrandingMode(b.brandingMode||b.mode);const whiteLabel=brandMode==='whitelabel';const moduleTitle=m.title||'CLARITY';$('heroProduct').textContent=whiteLabel?`${b.brandName||'Company'} ${moduleTitle.replace(/^CLARITY\s*/i,'')}`:moduleTitle;$('heroDescription').textContent=m.description||'';$('moduleIcon').textContent=m.icon||'CL';$('finalModuleIcon').textContent=m.icon||'CL';$('moduleTitle').textContent=m.title||'CLARITY';$('moduleDescription').textContent=m.description||'';$('finalModuleTitle').textContent=m.title||'CLARITY';$('finalModuleDescription').textContent=m.description||'';
  $('metaWorkflow').textContent=r.workflowKey||'—';$('metaMode').textContent=modeName(r.mode);$('metaLanguage').textContent=langName(r.participantLang);$('metaPurpose').textContent=r.position||r.purpose||t('noInfo');$('metaQuestions').textContent=t('questions',r.questionCount);$('metaUid').textContent=r.uid||'—';
  $('summaryCompany').textContent=b.brandName||b.companyId||'CLARITY';$('summaryReport').textContent=langName(r.reportLang);$('summaryUnits').textContent=String(r.requiredUnits??0);$('summaryStatus').textContent=r.status||'—';
  $('moduleReadiness').textContent=m.startEnabled?t('routerReady'):t('modulePending');$('moduleDevice').textContent=t('responsive');$('finalWorkflow').textContent=r.workflowKey||'—';$('finalStatus').textContent=m.readiness||'—';$('startModuleBtn').disabled=!m.startEnabled;$('mediaConsentRow').classList.toggle('hidden',!m.media);
  const isInterview=String(r.productKey||'').toLowerCase()==='interview';document.body.classList.toggle('interview-product',isInterview);
  ['metaWorkflow','metaUid'].forEach(id=>$(id)?.closest('.meta')?.classList.toggle('interview-technical-hidden',isInterview));
  ['summaryUnits','summaryStatus'].forEach(id=>$(id)?.closest('.summary-row')?.classList.toggle('interview-technical-hidden',isInterview));
  $('statusBtn')?.classList.toggle('hidden',isInterview);
  if(isInterview){$('moduleViewText').textContent=t('interviewReady');$('moduleNotice').textContent=t('interviewOpenNotice');$('startModuleBtn').textContent=t('openInterview')}
  applyBranding(b);
}
async function apiRaw(path,{method='POST',body=null,query={},timeoutMs=120000}={}){
  const url=new URL(`${API_BASE}/${path}`);
  Object.entries(query).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')url.searchParams.set(k,v)});
  const controller=typeof AbortController!=='undefined'?new AbortController():null;
  const boundedTimeout=Math.max(5000,Math.min(180000,Number(timeoutMs)||120000));
  const startedAt=Date.now();
  const timer=controller?setTimeout(()=>controller.abort(),boundedTimeout):null;
  try{
    const response=await fetch(url,{method,headers:{'Content-Type':'application/json','Accept':'application/json'},body:body?JSON.stringify(body):undefined,credentials:'omit',cache:'no-store',signal:controller?.signal});
    const data=await response.json().catch(()=>({}));
    if(!response.ok||data?.ok===false){
      const errorPayload=typeof data?.error==='object'?data.error:{};
      const e=new Error(errorPayload.message||data?.message||`HTTP ${response.status}`);
      e.code=errorPayload.code||data?.code||data?.error||`HTTP_${response.status}`;
      e.details=errorPayload.details||data?.details||null;
      e.httpStatus=response.status;e.durationMs=Date.now()-startedAt;throw e
    }
    return data
  }catch(error){
    if(error?.name==='AbortError'){
      const e=new Error(`Request '${path}' timed out after ${boundedTimeout} ms.`);
      e.code='UNIVERSAL_API_TIMEOUT';e.transport=true;e.path=path;e.timeoutMs=boundedTimeout;e.durationMs=Date.now()-startedAt;throw e
    }
    throw error
  }finally{if(timer)clearTimeout(timer)}
}
function isUniversalTokenError(error){return['UNIVERSAL_TOKEN_INVALID','UNIVERSAL_TOKEN_NONCE_MISMATCH','UNIVERSAL_TOKEN_SCOPE_INVALID','UNIVERSAL_TOKEN_UID_MISMATCH','UNIVERSAL_TOKEN_COMPANY_MISMATCH','UNIVERSAL_TOKEN_ACCESS_MISMATCH'].includes(String(error?.code||''))}
async function refreshUniversalToken(){if(tokenRefreshPromise)return tokenRefreshPromise;tokenRefreshPromise=(async()=>{const data=await apiRaw('v2AppBootstrap',{method:'GET',query:{uid:state.uid,userAgent:navigator.userAgent,deviceClass:deviceClass()}});if(!data?.token)throw Object.assign(new Error('The Universal App session could not be renewed.'),{code:'UNIVERSAL_TOKEN_REFRESH_FAILED'});state.token=data.token;state.payload={...(state.payload||{}),...data,runtime:{...(state.payload?.runtime||{}),...(data.runtime||{})},branding:data.branding||state.payload?.branding};state.module=resolveModuleView(state.payload,state.locale);renderPayload();return state.token})().finally(()=>{tokenRefreshPromise=null});return tokenRefreshPromise}
async function api(path,options={}){const request={method:options.method||'POST',body:options.body?{...options.body}:null,query:{...(options.query||{})},timeoutMs:options.timeoutMs};try{return await apiRaw(path,request)}catch(error){if(path==='v2AppBootstrap'||!isUniversalTokenError(error))throw error;await refreshUniversalToken();if(request.body&&('token'in request.body||'sessionToken'in request.body)){request.body.token=state.token;delete request.body.sessionToken}return apiRaw(path,request)}}
function deviceClass(){const w=Math.min(screen.width||innerWidth,innerWidth);return w<600?'mobile':w<1024?'tablet':'desktop'}
function prefill(){const p=state.payload?.runtime?.candidateProfile||{};$('firstName').value=p.firstName||'';$('lastName').value=p.lastName||'';$('email').value=p.email||'';$('externalReference').value=p.externalReference||''}
async function fail(error){document.body.classList.remove('interview-production-mode');try{await applyBranding({brandingMode:'clarity',brandName:'CLARITY',legalProductName:'CLARITY Decision Intelligence Platform',logoUrl:'./assets/clarity-logo.png'})}catch(_){}revealApp();show('errorView');$('errorText').textContent=error?.message||t('unavailableText');$('errorCode').textContent=error?.code||'UNIVERSAL_APP_ERROR'}
async function bootstrap(){if(!state.uid)return fail({code:'UNIVERSAL_UID_REQUIRED',message:t('unavailableText')});try{const data=await api('v2AppBootstrap',{method:'GET',query:{uid:state.uid,userAgent:navigator.userAgent,deviceClass:deviceClass()}});state.payload=data;state.token=data.token||'';state.participantLocale=normalizeUiLocale(data.runtime?.participantLang||data.runtime?.userCommLang||'en');state.locale=state.participantLocale;state.module=resolveModuleView(data,state.locale);prefill();applyLocale();await applyBranding(data.branding||data.runtime?.brandingSnapshot||{});setStep('welcome');show('welcomeView');revealApp()}catch(e){await fail(e)}}
async function saveProfile(){const profile={firstName:$('firstName').value.trim(),lastName:$('lastName').value.trim(),email:$('email').value.trim(),externalReference:$('externalReference').value.trim()};if(!profile.firstName||!profile.lastName||!/^\S+@\S+\.\S+$/.test(profile.email))return alert(t('profileError'));$('saveProfileBtn').disabled=true;try{const data=await api('v2AppProfile',{body:{token:state.token,uid:state.uid,profile}});state.payload.runtime={...state.payload.runtime,...data.runtime};setStep('consent');show('consentView')}catch(e){alert(e.message||t('genericError'))}finally{$('saveProfileBtn').disabled=false}}
async function saveConsent(){const mediaOk=!state.module?.media||$('mediaConsent').checked;if(!$('privacyConsent').checked||!$('aiConsent').checked||!mediaOk)return alert(t('consentError'));$('saveConsentBtn').disabled=true;try{const data=await api('v2AppConsent',{body:{token:state.token,uid:state.uid,accepted:true,privacyAccepted:true,aiInteractionAccepted:true,mediaAccepted:state.module?.media===true,version:'universal-consent-v1'}});state.payload.runtime={...state.payload.runtime,...data.runtime};renderPayload();setStep('module');show('moduleView')}catch(e){alert(e.message||t('genericError'))}finally{$('saveConsentBtn').disabled=false}}
async function refreshStatus(){try{const data=await api('v2AppStatus',{body:{token:state.token,uid:state.uid}});state.payload={...state.payload,...data};state.module=resolveModuleView(state.payload,state.locale);renderPayload()}catch(e){alert(e.message||t('genericError'))}}
async function startModule(){if(!state.module?.startEnabled)return alert(t('modulePendingAlert'));if(state.payload?.runtime?.productKey==='cv_analysis')return cvModule.activate();if(state.payload?.runtime?.productKey==='video_presentation')return vpModule.activate();if(state.payload?.runtime?.productKey==='ai_literacy')return aiLiteracyModule.activate();if(['assessment','snapshot'].includes(state.payload?.runtime?.productKey))return assessmentModule.activate();if(state.payload?.runtime?.productKey==='interview')return interviewModule.activate();alert(t('modulePendingAlert'))}
function wire(){
  $('langBtn').addEventListener('click',()=>{state.locale=state.locale===state.participantLocale?'en':state.participantLocale;applyLocale()});$('supportBtn').addEventListener('click',()=>{location.href='mailto:info@clarity-nvl.com'});$('continueProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('backWelcomeBtn').addEventListener('click',()=>{setStep('welcome');show('welcomeView')});$('saveProfileBtn').addEventListener('click',saveProfile);$('backProfileBtn').addEventListener('click',()=>{setStep('profile');show('profileView')});$('saveConsentBtn').addEventListener('click',saveConsent);$('statusBtn').addEventListener('click',refreshStatus);$('startModuleBtn').addEventListener('click',startModule);
}
cvModule=createCvModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});vpModule=createVideoPresentationModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});aiLiteracyModule=createAiLiteracyModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});assessmentModule=createAssessmentModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});interviewModule=createInterviewModule({$,state,api,show,setStep,getLocale:()=>state.locale,onFatal:fail});wire();applyLocale();bootstrap();
